MAPPING = {"D1": "'dul ba gzhi",
"D2": "so sor thar ba'i mdo",
"D3": "'dul ba rnam par 'byed pa",
"D4": "dge slong ma'i so sor thar ba'i mdo",
"D5": "dge slong ma'i 'dul ba rnam par 'byed pa",
"D6": "'dul ba phran tshegs kyi gzhi",
"D7": "'dul ba gzhung dam pa rdzogs te u pa lis kun dris pa rdzogs so",
"D7a": "'dul ba gzhung dam pa",
"D8": "shes rab kyi pha rol tu phyin pa stong phrag brgya pa",
"D9": "shes rab kyi pha rol tu phyin pa stong phrag nyi shu lnga pa",
"D10": "'phags pa shes rab kyi pha rol tu phyin pa khri brgyad stong pa zhes bya ba theg pa chen po'i mdo",
"D11": "'phags pa shes rab kyi pha rol tu phyin pa khri pa zhes bya ba theg pa chen po'i mdo",
"D12": "'phags pa shes rab kyi pha rol tu phyin pa brgyad stong pa",
"D13": "'phags pa shes rab kyi pha rol tu phyin pa sdud pa tshigs su bcad pa",
"D14": "'phags pa rab kyi rtsal gyis rnam par gnon pas zhus pa shes rab kyi pha rol tu phyin pa bstan pa",
"D15": "'phags pa shes rab kyi pha rol tu phyin pa lnga brgya pa",
"D16": "'phags pa shes rab kyi pha rol tu phyin pa rdo rje gcod pa zhes bya ba theg pa chen po'i mdo",
"D17": "'phags pa shes rab kyi pha rol tu phyin pa'i tshul brgya lnga bcu pa rdzogs so",
"D18": "'phags pa bcom ldan 'das ma shes rab kyi pha rol tu phyin pa lnga bcu pa",
"D19": "'phags pa shes rab kyi pha rol tu phyin pa kau shi ka zhes bya'o",
"D20": "'phags pa shes rab kyi pha rol tu phyin pa'i sgo nyi shu rtsa lnga pa zhes bya ba theg pa chen po'i mdo",
"D21": "bcom ldan 'das ma shes rab kyi pha rol tu phyin pa'i snying po",
"D22": "'phags pa shes rab kyi pha rol tu phyin pa yi ge nyung ngu zhes bya ba'i theg pa chen po'i mdo",
"D23": "de bzhin gshegs pa thams cad kyi yum shes rab kyi pha rol tu phyin ma yi ge gcig ma zhes bya ba",
"D24": "'phags pa shes rab kyi pha rol tu phyin pa bdun brgya pa zhes bya ba theg pa chen po'i mdo",
"D25": "'phags pa shes rab kyi pha rol tu phyin pa'i mtshan brgya rtsa brgyad pa zhes bya ba",
"D26": "'phags pa shes rab kyi pha rol tu phyin pa nyi ma'i snying po'i theg pa chen po'i mdo",
"D27": "'phags pa zla ba'i snying po shes rab kyi pha rol tu phyin pa theg pa chen po'i mdo",
"D28": "'phags pa shes rab kyi pha rol tu phyin pa kun tu bzang po theg pa chen po'i mdo",
"D29": "'phags pa shes rab kyi pha rol tu phyin pa lag na rdo rje'i mdo theg pa chen po",
"D30": "'phags pa shes rab kyi pha rol tu phyin pa rdo rje rgyal mtshan gyi mdo theg pa chen po",
"D31": "chos kyi 'khor lo rab tu bskor ba'i mdo",
"D32": "skyes pa rabs kyi gleng gzhi",
"D33": "lcang lo can gyi pho brang gi mdo",
"D34": "'dus pa chen po'i mdo",
"D35": "byams pa'i mdo",
"D36": "byams pa bsgom pa'i mdo",
"D37": "bslab pa lnga'i phan yon gyi mdo",
"D38": "ri'i kun dga' bo'i mdo",
"D39": "klu'i rgyal po dga' bo nyer dga' 'dul ba'i mdo",
"D40": "'od srung chen po'i mdo",
"D41": "nyi ma'i mdo",
"D42": "zla ba'i mdo",
"D43": "bkra shis chen po'i mdo",
"D44": "sangs rgyas phal po che zhes bya ba shin tu rgyas pa chen po'i mdo",
"D45": "sdom pa gsum bstan pa'i le'u zhes bya ba theg pa chen po'i mdo",
"D46": "'phags pa sgo mtha' yas pa rnam par sbyong ba bstan pa'i le'u zhes bya ba theg pa chen po'i mdo",
"D47": "'phags pa de bzhin gshegs pa'i gsang ba bsam gyis mi khyab pa bstan pa zhes bya ba theg pa chen po'i mdo",
"D48": "'phags pa rmi lam bstan pa zhes bya ba theg pa chen po'i mdo",
"D49": "'phags pa 'od dpag med kyi bkod pa zhes bya ba theg pa chen po'i mdo",
"D50": "'phags pa de bzhin gshegs pa mi 'khrugs pa'i bkod pa zhes bya ba theg pa chen po'i mdo",
"D51": "'phags pa go cha'i bkod pa bstan pa zhes bya ba theg pa chen po'i mdo",
"D52": "'phags pa chos kyi dbyings kyi rang bzhin dbyer med pa bstan pa zhes bya ba theg pa chen po'i mdo",
"D53": "'phags pa chos bcu pa zhes bya ba theg pa chen po'i mdo",
"D54": "'phags pa kun nas sgo'i le'u zhes bya ba theg pa chen po'i mdo",
"D55": "'phags pa 'od zer kun du bkye ba bstan pa zhes bya ba theg pa chen po'i mdo",
"D56": "'phags pa byang chub sems dpa'i sde snod ces bya ba theg pa chen po'i mdo",
"D57": "'phags pa dga' bo la mngal na gnas pa bstan pa zhes bya ba",
"D58": "'phags pa tshe dang ldan pa dga' bo mngal du 'jug par bstan pa zhes",
"D59": "'phags pa 'jam dpal gyi sangs rgyas kyi zhing gi yon tan bkod pa zhes bya ba",
"D60": "'phags pa yab dang sras mjal ba zhes",
"D61": "'phags pa gang pos zhus pa zhes",
"D62": "'phags pa yul 'khor skyong gis zhus pa zhes bya ba",
"D63": "'phags pa khyim bdag drag shul can gyis zhus pa zhes",
"D64": "'phags pa glog thob kyis zhus pa zhes",
"D65": "'phags pa sgyu ma mkhan bzang po lung bstan pa zhes",
"D66": "'phags pa cho 'phrul chen po bstan pa zhes",
"D67": "'phags pa byams pa'i seng ge'i sgra chen po zhes",
"D68": "'phags pa 'dul ba rnam par gtan la dbab pa nye bar 'khor gyis zhus pa zhes",
"D69": "'phags pa lhag pa'i bsam pa bskul ba zhes",
"D70": "'phags pa lag bzangs kyis zhus pa zhes",
"D71": "'phags pa nges pas zhus pa zhes",
"D72": "'phags pa khyim bdag dpas byin gyis zhus pa zhes",
"D73": "'phags pa bat sa'i rgyal po char byed kyis zhus pa zhes",
"D74": "'phags pa bu mo blo gros bzang mos zhus pa zhes",
"D75": "'phags pa gang 'ga'i mchog gis zhus pa zhes",
"D76": "'phags pa mya ngan med kyis byin pa lung bstan pa zhes",
"D77": "'phags pa dri ma med kyis byin pas zhus pa zhes",
"D78": "'phags pa yon tan rin po che me tog kun tu rgyas pas zhus pa zhes",
"D79": "'phags pa sangs rgyas kyi yul bsam gyis mi khyab pa bstan pa zhes bya ba",
"D80": "'phags pa lha'i bu blo gros rab gnas kyis zhus pa zhes bya ba theg pa chen po'i mdo",
"D81": "'phags pa seng ges zhus pa zhes bya ba theg pa chen po'i mdo",
"D82": "'phags pa sangs rgyas thams cad kyi gsang chen thabs la mkhas pa byang chub sems dpa' ye shes dam pas zhus pa'i le'u zhes bya ba theg pa chen po'i mdo",
"D83": "'phags pa tshong dpon bzang skyong gyis zhus pa zhes bya ba theg pa chen po'i mdo",
"D84": "'phags pa bu mo rnam dag dad bas zhus pa zhes bya ba theg pa chen po'i mdo",
"D85": "'phags pa byams pas zhus pa zhes bya ba theg pa chen po'i mdo",
"D86": "'phags pa byams pas zhus pa zhes bya ba theg pa chen po'i mdo",
"D87": "'phags pa 'od srung gi le'u zhes bya ba theg pa chen po'i mdo",
"D88": "'phags pa rin po che'i phung bo zhes bya ba theg pa chen po'i mdo",
"D89": "'phags pa blo gros mi zad pas zhus pa zhes bya ba theg pa chen po'i mdo",
"D90": "'phags pa shes rab kyi pha rol tu phyin pa bdun brgya pa zhes bya ba theg pa chen po'i mdo",
"D91": "'phags pa gtsug na rin po ches zhus pa zhes bya ba theg pa chen po'i mdo",
"D92": "'phags pa lha mo dpal 'phreng gi seng ge'i sgra zhes bya ba theg pa chen po'i mdo",
"D93": "'phags pa drang srong rgyas pas zhus pa zhes bya ba theg pa chen po'i mdo",
"D94": "'phags pa bskal pa bzang po zhes bya ba theg pa chen po'i mdo",
"D95": "'phags pa rgya cher rol pa zhes bya ba theg pa chen po'i mdo",
"D96": "'phags pa 'jam dpal rnam par rol pa zhes bya ba theg pa chen po'i mdo",
"D97": "'phags pa 'jam dpal rnam par 'phrul ba'i le'u zhes bya ba theg pa chen po'i mdo",
"D98": "'phags pa de bzhin gshegs pa thams cad kyi byin gyi rlabs sems can la gzigs shing sangs rgyas kyi zhing gi bkod pa kun tu ston pa zhes bya ba theg pa chen po'i mdo",
"D99": "'phags pa bcom ldan 'das kyi ye shes rgyas pa'i mdo sde rin po che mtha' yas pa mthar phyin pa zhes bya ba theg pa chen po'i mdo",
"D100": "'phags pa sangs rgyas thams cad kyi yul la 'jug pa'i ye shes snang ba'i rgyan ces bya ba theg pa chen po'i mdo",
"D101": "'phags pa dge ba'i rtsa ba yongs su 'dzin pa zhes bya ba theg pa chen po'i mdo",
"D102": "'phags pa zung gi mdo'i chos kyi rnam grangs / ['phags pa dge 'dun] zung gi mdo'i chos kyi rnam grangs",
"D103": "'phags pa khye'u snang ba bsam gyis mi khyab pas bstan pa zhes bya ba'i chos kyi rnam grangs",
"D104": "'phags pa de bzhin gshegs pa rnams kyi sangs rgyas kyi zhing gi yon tan brjod pa'i chos kyi rnam grangs",
"D105": "'phags pa dkyil 'khor brgyad pa zhes bya ba'i chos kyi rnam grangs theg pa chen po'i mdo",
"D106": "'phags pa dgongs pa nges par 'grel pa zhes bya ba theg pa chen po'i mdo",
"D107": "'phags pa lang kar gshegs pa'i theg pa chen po'i mdo",
"D108": "'phags pa lang kar gshegs pa rin po che'i mdo las sangs rgyas thams cad kyi gsung gi snying po zhes bya ba'i le'u",
"D109": "'phags pa ga ya mgo'i ri zhes bya ba theg pa chen po'i mdo",
"D110": "'phags pa rgyan stug po bkod pa zhes bya ba theg pa cen po'i mdo",
"D111": "'phags pa snying rje chen po'i pad ma dkar po zhes bya ba theg pa chen po'i mdo",
"D112": "'phags pa snying rje pad ma dkar po zhes bya ba theg pa chen po'i mdo",
"D113": "dam pa'i chos pad ma dkar po zhes bya ba theg pa chen po'i mdo",
"D114": "'phags pa chos thams cad kyi yon tan bkod pa'i rgyal po zhes bya ba theg pa chen po'i mdo",
"D115": "'phags pa bde ba can gyi bkod pa zhes bya ba theg pa chen po'i mdo",
"D116": "'phags pa za ma tog bkod pa zhes bya ba theg pa chen po'i mdo",
"D117": "'phags pa dkon mchog gi za ma tog ces bya ba theg pa chen po'i mdo",
"D118": "'phags pa rin po che'i mtha' zhes bya ba theg pa chen po'i mdo",
"D119": "'phags pa yongs su mya ngan las 'das pa chen po'i mdo",
"D120": "'phags pa yongs su mya ngan las 'das pa chen po'i mdo",
"D121": "'phags pa yongs su mya ngan las 'das pa chen po'i mdo",
"D122": "'phags pa 'da' kha ye shes zhes bya ba theg pa chen po'i mdo",
"D123": "sangs rgyas kyi mdzod kyi chos kyi yi ge ming gcig ni chos so cog las gdams",
"D124": "'phags pa dkon mchog 'byung gnas zhes bya ba theg pa chen po'i mdo",
"D125": "'phags pa gser gyi mdo zhes bya ba theg pa chen po'i mdo",
"D126": "'phags pa gser gyi bye ma lta bu zhes bya ba theg pa chen po'i mdo",
"D127": "'phags pa chos thams cad kyi rang bzhin mnyam pa nyid rnam par spros pa ting nge 'dzin gyi rgyal po zhes bya ba theg pa chen po'i mdo",
"D128": "'phags pa chos nyid rang gi ngo bo stong pa nyid las mi g.yo bar tha dad par thams cad la snang ba'i mdo",
"D129": "'phags pa rab tu zhi ba rnam par nges pa'i cho 'phrul gyi ting nge 'dzin zhes bya ba theg pa chen po'i mdo",
"D130": "'phags pa sgyu ma lta bu'i ting nge 'dzin ces bya ba theg pa chen po'i mdo",
"D131": "'phags pa de bzhin gshegs pa'i ye shes kyi phyag rgya'i ting nge 'dzin ces bya ba theg pa chen po'i mdo",
"D132": "'phags pa dpa' bar 'gro ba'i ting nge 'dzin ces bya ba theg pa chen po'i mdo",
"D133": "'phags pa da ltar gyi sangs rgyas mngon sum du bzhugs pa'i ting nge 'dzin ces bya ba theg pa chen po'i mdo",
"D134": "'phags pa bsod nams thams cad bsdus pa'i ting nge 'dzin ces bya ba theg pa chen po'i mdo",
"D135": "rdo rje'i ting nge 'dzin gyi chos kyi yi ge",
"D136": "'phags pa khye'u bzhi'i ting nge 'dzin ces bya ba theg pa chen po'i mdo",
"D137": "'phags pa ting nge 'dzin mchog dam pa",
"D138": "'phags pa 'dus pa chen po rin po che tog gi gzungs zhes bya ba theg pa chen po'i mdo",
"D139": "'phags pa rdo rje'i snying po'i gzungs zhes bya ba theg pa chen po'i mdo",
"D140": "'phags pa sgo mtha' yas pa sgrub pa zhes bya ba'i gzungs",
"D141": "'phags pa sgo drug pa zhes bya ba'i gzungs",
"D142": "'phags pa rnam par mi rtog par 'jug pa zhes bya ba'i gzungs",
"D143": "tshigs su bcad pa gnyis pa'i gzungs",
"D144": "'phags pa theg pa chen po la dad pa rab tu sgom pa zhes bya ba theg pa chen po'i mdo",
"D145": "'phags pa dkon mchog ta la la'i gzungs zhes bya ba theg pa chen po'i mdo",
"D146": "'phags pa byang chub sems dpa'i spyod yul gyi thabs kyi yul la rnam par 'phrul ba bstan pa zhes bya ba theg pa chen po'i mdo",
"D147": "'phags pa de bzhin gshegs pa'i snying rje chen po nges par bstan pa zhes bya ba thag pa chen po'i mdo",
"D148": "'phags pa nam mkha'i mdzod kyis zhus pa zhes bya ba theg pa chen po'i mdo",
"D149": "'phags pa byams pas zhus pa zhes bya ba theg pa chen po'i mdo",
"D150": "'phags pa spyan ras gzigs dbang phyug gis zhus pa chos bdun pa zhes bya ba theg pa chen po'i mdo",
"D151": "'phags pa spobs pa'i blo gros kyis zhus pa zhes bya ba theg pa chen po'i mdo",
"D152": "'phags pa blo gros rgya mtshos zhus ba zhes bya ba theg pa chen po'i mdo",
"D153": "'phags pa klu'i rgyal po rgya mtshos zhus pa zhes bya ba theg pa chen po'i mdo",
"D154": "'phags pa klu'i rgyal po rgya mtshos zhus pa zhes bya ba theg pa chen po'i mdo",
"D155": "'phags pa klu'i rgyal po rgya mtshos zhus pa zhes bya ba theg pa chen po'i mdo",
"D156": "'phags pa klu'i rgyal po ma dros pas zhus pa zhes bya ba theg pa chan po'i mdo",
"D157": "'phags pa mi 'am ci'i rgyal po sdong pos zhus pa zhes bya ba theg pa chen po'i mdo",
"D158": "'phags pa tshangs pas zhus pa zhes bya ba theg pa chen po'i mdo",
"D159": "'phags pa tshangs pas byin gyis zhus pa zhes bya ba theg pa chen po'i mdo",
"D160": "'phags pa tshangs pa khyad par sems kyis zhus pa zhes bya ba theg pa chen po'i mdo",
"D161": "'phags pa lha'i bu rab rtsal sems kyis zhus pa zhes bya ba theg pa chen po'i mdo",
"D162": "'phags pa dpal dbyig gis zhus pa zhes bya ba theg pa chen po'i mdo",
"D163": "'phags pa rin chen dra ba can gyis zhus pa zhes bya ba theg pa chan po'i mdo",
"D164": "'phags pa rin chen zla bas zhus pa zhes bya ba theg pa chen po'i mdo",
"D165": "'phags pa bde byed kyis zhus pa zhes bya ba theg pa chen po'i mdo",
"D166": "'phags pa yul 'khor skyong gis zhus pa zhes bya ba theg pa chen po'i mdo",
"D167": "'phags pa rnam par 'phrul pa'i rgyal pos zhus pa zhes bya ba theg pa chen po'i mdo",
"D168": "dri ma med pa'i 'od kyis zhus pa",
"D169": "'phags pa theg pa chen po'i man ngag ces bya ba theg pa chen po'i mdo",
"D170": "'phags pa bram ze mo dpal ldan mas zhus pa zhes bya ba theg pa chen po'i mdo",
"D171": "'phags pa bgres mos zhus pa zhes bya ba theg pa chen po'i mdo",
"D172": "'phags pa 'jam dpal gyis dris pa zhes bya ba theg pa chen po'i mdo",
"D173": "'phags pa bdag med pa dris pa zhes bya ba theg pa chen po'i mdo",
"D174": "'phags pa 'jig rten 'dzin gyis yongs su dris pa zhes bya ba'i mdo",
"D175": "'phags pa blo gros mi zad pas bstan pa zhes bya ba theg pa chen po'i mdo",
"D176": "'phags pa dri ma med par grags pas bstan pa zhes bya ba theg pa chen po'i mdo",
"D177": "'phags pa 'jam dpal gyis bstan ba zhes bya ba theg pa chen po'i mdo",
"D178": "'phags pa byang chub kyi phyogs bstan pa zhes bya ba theg pa chen po'i mdo",
"D179": "'phags pa kun rdzob dang don dam pa'i bden pa bstan pa zhes bya ba theg pa chen po'i mdo",
"D180": "'phags pa chos thams cad 'byung ba med par bstan pa zhes bya ba theg pa chen po'i mdo",
"D181": "'phags pa pha rol tu phyin pa lnga bstan pa zhes bya ba theg pa chen po'i mdo",
"D182": "'phags pa sbyin pa'i pha rol tu phyin pa zhes bya ba theg pa chen po'i mdo",
"D183": "'phags pa sbyin pa'i phan yon bstan pa",
"D184": "'phags pa byang chub sems dpa'i spyod pa bstan pa zhes bya ba theg pa chen po'i mdo",
"D185": "'phags pa de bzhin gshegs pa'i yon tan dang ye shes bsam gyis mi khyab pa'i yul la 'jug pa bstan pa zhes bya ba theg pa chen po'i mdo",
"D186": "'phags pa sangs rgyas kyi stobs skyed pa'i cho 'phrul rnam par 'phrul ba bstan pa zhes bya ba theg pa chen po'i mdo",
"D187": "'phags pa sangs rgyas kyi chos bsam gyis mi khyab pa bstan pa",
"D188": "'phags pa mar me mdzad kyis lung bstan pa zhes bya ba theg pa chen po'i mdo",
"D189": "'phags pa tshangs pa'i dpal lung bstan pa zhes bya ba theg pa chen po'i mdo",
"D190": "'phags pa bud med 'gyur ba lung bstan pa zhes bya ba theg pa chen po'i mdo",
"D191": "'phags pa bu mo zla mchog lung bstan pa zhes bya ba theg pa chen po'i mdo",
"D192": "'phags pa bde ldan ma lung bstan pa zhes bya ba theg pa cen po'i mdo",
"D193": "'phags pa lha mo chen mo dpal lung bstan pa",
"D194": "'phags pa rgyal ba'i blo gros zhes bya ba theg pa chen po'i mdo",
"D195": "'phags pa spyan ras gzigs zhes bya ba theg pa chen po'i mdo",
"D196": "'phags pa 'jam dpal gnas pa zhes bya ba theg pa chen po'i mdo",
"D197": "'phags pa bdud rtsi brjod pa zhes bya ba theg pa chen po'i mdo",
"D198": "'phags pa byams pa 'jug pa zhes bya ba theg pa chen po'i mdo",
"D199": "'phags pa byang chub sems dpa' byams pa dga' ldan gnam du skye ba blangs po'i mdo",
"D200": "'phags pa 'jig rten gyi rjes su 'thun par 'jug pa zhes bya ba theg pa chen po'i mdo",
"D201": "'phags pa dad pa'i stobs bskyed pa la 'jug pa'i phyag rgya zhes bya ba theg pa chen po'i mdo",
"D202": "'phags pa nges pa dang ma nges par 'gro ba'i phyag rgya la 'jug pa zhes bya ba theg pa chen po'i mdo",
"D203": "'phags pa chos kyi phyag rgya zhes bya ba theg pa chen po'i mdo",
"D204": "'phags pa mar me 'bul ba zhes bya ba theg pa chen po'i mdo",
"D205": "'phags pa grong khyer gyis 'tsho ba zhes bya ba theg pa chen po'i mdo",
"D206": "zas kyi 'tsho ba rnam par dag pa zhes bya ba theg pa chen po'i mdo",
"D207": "glang po'i rtsal zhes bya ba theg pa chen po'i mdo",
"D208": "'phags pa sgra chen po zhes bya ba theg pa chen po'i mdo",
"D209": "'phags pa seng ge'i sgra bsgrags pa zhes bya ba theg pa chen po'i mdo",
"D210": "'phags pa sA lu'i ljang ba zhes bya ba theg pa chen po'i mdo",
"D211": "rten cing 'brel bar 'byung ba dang po dang rnam par dbye ba bstan pa zhes bya ba'i mdo",
"D212": "'phags pa rten cing 'brel bar 'byung ba zhes bya ba theg pa chen po'i mdo",
"D213": "'phags pa sor mo'i phreng ba la phan pa zhes bya ba theg pa chen po'i mdo",
"D214": "rgyal po la gdams pa zhes bya ba theg pa chen po'i mdo",
"D215": "rgyal po la gdams pa zhes bya ba theg pa chen po'i mdo",
"D216": "'phags pa ma skyes dgra'i 'gyod pa bsal ba zhes bya ba theg pa chen po'i mdo",
"D217": "'phags pa dpal sbas zhes bya ba'i mdo",
"D218": "'phags pa las kyi sgrib pa rnam par dag pa zhes bya ba theg pa chen po'i mdo",
"D219": "'phags pa las kyi sgrib pa rgyun gcod pa zhes bya ba theg pa chen po'i mdo",
"D220": "sangs rgyas kyi sde snod tshul khrims 'chal pa tshar gcod pa zhes bya ba theg pa chen po'i mdo",
"D221": "'phags pa rgyal po la gdams pa zhes bya ba theg pa chen po'i mdo",
"D222": "'phags pa rnga bo che chen po'i le'u zhes bya ba theg pa chen po'i mdo",
"D223": "'phags pa sum bcu rtsa gsum pa'i le'u zhes bya ba theg pa chen po'i mdo",
"D224": "'phags pa lhag pa'i bsam pa brtan pa'i le'u zhes bya ba theg pa chen po'i mdo",
"D225": "'phags pa gsum la skyabs su 'gro ba zhes bya ba theg pa chen po'i mdo",
"D226": "'phags pa srid pa 'pho ba zhes bya ba theg pa chen po'i mdo",
"D227": "'phags pa rnam par 'thag pa thams cad bsdus pa zhes bya ba theg pa chen po'i mdo",
"D228": "'phags pa sangs rgyas bgro ba zhes bya ba theg pa chen po'i mdo",
"D229": "de bzhin gshegs pa bgro ba zhes bya ba theg pa chen po'i mdo",
"D230": "'dus pa chen po theg pa chen po'i mdo sde las de bzhin gshegs pa'i dpal gyi dam tshig ces bya ba theg pa chen po'i mdo",
"D231": "'phags pa dkon mchog sprin ces bya ba theg pa chen po'i mdo",
"D232": "'phags pa sprin chen po zhes bya ba thag pa chen po'i mdo",
"D233": "'phags pa sprin chen po'i mdo las phyogs bcu'i byang chub sems dpa' rgya mtsho 'dus pa'i dga' ston chen po la rtse ba zhes bya ba'i le'u",
"D234": "'phags pa sprin chen po rlung gi dkyil 'khor gyi le'u klu thams cad kyi snying po zhes bya ba theg pa chen po'i mdo",
"D235": "'phags pa sprin chen po",
"D236": "bcom ldan 'das kyi gtsug gtor chen po de bzhin gshegs pa'i gsang ba sgrub pa'i don mngon par thob pa'i rgyu byang chub sems dpa' thams cad kyi spyod pa dpa' bar 'gro ba'i mdo le'u stong phrag bcu pa las le'u bcu pa",
"D237": "gtsug tor chen po bam po dgu pa las bdud kyi le'u nyi tshe 'byung ba",
"D238": "'phags pa chos yang dag par sdud pa zhes bya ba theg pa chen po'i mdo",
"D239": "'dus pa chen po las sa'i snying po'i 'khor lo bcu pa zhes bya ba theg pa chen po'i mdo",
"D240": "'phags pa phyir mi ldog pa'i 'khor lo zhes bya ba theg pa chen po'i mdo",
"D241": "'phags pa ting nge 'dzin gyi 'khor lo zhes bya ba theg pa chen po'i mdo",
"D242": "'phags pa yongs su bsngo ba'i 'khor lo zhes bya ba theg pa chen po'i mdo",
"D243": "dam pa'i chos kyi rgyal po theg pa chen po'i mdo",
"D244": "'phags pa chos kyi tshul zhes bya ba theg pa chen po'i mdo",
"D245": "'phags pa chos kyi phung po zhes bya ba theg pa chen po'i mdo",
"D246": "'phags pa don dam pa'i chos kyi rnam par rgyal ba zhes bya ba theg pa chen po'i mdo",
"D247": "'phags pa chos dang don rnam par 'byed pa zhes bya ba theg pa chen po'i mdo",
"D248": "byang chub sems dpa'i so sor thar ba chos bzhi sgrub pa zhes bya ba theg pa chen po'i mdo",
"D249": "'phags pa chos bzhi bstan pa zhes bya ba theg pa chen po'i mdo",
"D250": "chos bzhi pa'i mdo",
"D251": "'phags pa chos bzhi pa zhes bya ba theg pa chen po'i mdo",
"D252": "'phags pa bzhi pa sgrub pa zhes bya ba theg pa chen po'i mdo",
"D253": "chos gsum pa zhes bya ba'i mdo",
"D254": "'phags pa chos kyi rgyal mtshan gyi mdo theg pa chen po",
"D255": "theg pa chen po'i mdo chos rgya mtsho zhes bya ba",
"D256": "chos kyi rgya mo sangs rgyas rnam par snang mdzad kyis byang chub sems dpa'i sems kyi gnas bshad pa le'u bcu",
"D257": "'phags pa shin tu rgyas pa chen po'i sde nyi ma'i snying po zhes bya ba'i mdo",
"D258": "'phags pa de bzhin gshegs pa'i snying po zhes bya ba theg pa chen po'i mdo",
"D259": "'phags pa yi ge med pa'i za ma tog rnam par snang mdzad kyi snying po zhes bya ba theg pa chen po'i mdo",
"D260": "'phags pa nam mkha'i snying po zhes bya ba theg pa chen po'i mdo",
"D261": "'phags pa thabs mkhas pa zhes bya ba theg pa chen po'i mdo",
"D262": "sangs rgyas kyi mtshan lnga stong bzhi brgya lnga bcu rtsa gsum pa",
"D263": "'phags pa yang dag par spyod pa'i tshul nam mkha'i mdog gis 'dul ba'i bzod pa zhes bya ba theg pa chen po'i mdo",
"D264": "'phags pa thar pa chen po phyogs su rgyas pa 'gyod tshangs kyis sdig sbyangs te sangs rgyas su grub par rnam par bkod pa zhes bya ba theg pa chen po'i mdo",
"D265": "'phags pa rtogs pa chen po yongs su rgyas pa'i mdo las phyag 'tshal ba'i cho ga dang mtshan nas brjod pa'i yon tan gyi gleng gzhi dang dus gsum gyi de bzhin gshegs pa rnams kyi mtshan dang mdo sde bcu gnyis dang byang chub sems dpa' rnams kyi mtshan nas brjod cing phyag 'tshal ba dang bshags pa'i le'u rnams 'byung ba nyi tshe bcos shing bsgyur ba",
"D266": "'phags pa me tog gi tshogs zhes bya ba theg pa chen po'i mdo",
"D267": "dpang skong phyag brgya pa zhes bya ba",
"D268": "'phags pa bsam gyis mi khyab pa'i rgyal po'i mdo zhes bya ba theg pa chen po'i mdo",
"D269": "'phags pa phyogs bcu'i mun pa rnam par sel ba zhes bya ba theg pa chen po'i mdo",
"D270": "'phags pa sangs rgyas bdun pa zhes bya ba theg pa chen po'i mdo",
"D271": "'phags pa sangs rgyas brgyad pa zhes bya ba theg pa chen po'i mdo",
"D272": "sangs rgyas bcu pa zhes bya ba theg pa chen po'i mdo",
"D273": "'phags pa sangs rgyas bcu gnyis pa zhes bya ba theg pa chen po'i mdo",
"D274": "'phags pa sangs rgyas kyi dbu rgyan zhes bya ba theg pa chen po'i mdo chos kyi rnam grangs chen po",
"D275": "'phags pa sangs rgyas kyi sa zhes bya ba theg pa chen po'i mdo",
"D276": "'phags pa sangs rgyas mi spang ba zhes bya ba theg pa chen po'i mdo",
"D277": "'phags pa dkyil 'khor brgyad pa zhes bya ba theg pa chen po'i mdo",
"D278": "'phags pa bkra shis brgyad pa zhes bya ba theg pa chen po'i mdo",
"D279": "'phags pa sangs rgyas rjes su dran pa [dkon mchog gsum rjes su dran pa'i mdo]",
"D280": "chos rjes su dran pa [dkon mchog gsum rjes su dran pa'i mdo]",
"D281": "dge 'dun rjes su dran pa [dkon mchog gsum rjes su dran pa'i mdo]",
"D282": "bslab pa gsum gyi mdo",
"D283": "'phags pa sku gsum zhes bya ba theg pa chen po'i mdo",
"D284": "'phags pa phung po gsum pa zhes bya ba theg pa chen po'i mdo",
"D285": "'phags pa bsam pa thams cad yongs su rdzogs par byed pa zhes bya ba'i yongs su bsngo ba",
"D286": "'phags pa 'gro ba thams cad yongs su skyob par byed pa zhes bya ba'i yongs su bsngo ba",
"D287": "'phags pa dam pa'i chos dran pa nye bar gzhag pa",
"D288": "mdo chen po sgyu ma'i dra ba zhes bya ba",
"D289": "mdo chen po gzugs can snying pos bsu ba zhes bya ba",
"D290": "mdo chen po stong pa nyid ces bya ba",
"D291": "mdo chen po stong pa nyid chen po zhes bya ba",
"D292": "mdo chen po rgyal mtshan mchog ces bya ba",
"D293": "mdo chen po rgyal mtshan dam pa zhes bya ba",
"D294": "mdo chen po lnga gsum pa zhes bya ba",
"D295": "'phags pa rdo 'phangs pa'i mdo",
"D296": "gzhon nu dpe'i mdo",
"D297": "khams mang po'i mdo",
"D298": "gaN Di'i mdo",
"D299": "gaN Ti'i dus kyi mdo",
"D300": "'phags pa dge ba'i bshes gnyen bsten pa'i mdo",
"D301": "mngon par 'byung ba'i mdo",
"D302": "dge slong la rab tu gces pa'i mdo zhes bya ba",
"D303": "tshul khrims yang dag par ldan pa'i mdo",
"D304": "ltung ba sde lnga'i dge ba dang mi dge ba'i 'bras bu brtag pa'i mdo",
"D305": "mchog tu gdags pa'i mdo",
"D306": "rnam par grol ba'i lam las sbyangs pa'i yon tan bstan pa zhes bya ba",
"D307": "tshe'i mtha'i mdo",
"D308": "tshe 'pho ba ji ltar 'gyur ba zhus pa'i mdo",
"D309": "mi rtag pa nyid kyi mdo",
"D310": "mi rtag pa nyid kyi mdo",
"D311": "'phags pa 'du shes bcu gcig bstan pa'i mdo",
"D312": "'phags pa yangs pa'i grong khyer du 'jug pa'i mdo chen po",
"D313": "'phags pa mtshan mo bzang po zhes bya ba'i mdo",
"D314": "mun gyi nags tshal gyi sgo zhes bya ba'i mdo",
"D315": "pha ma'i mdo",
"D316": "'phags pa bden pa bzhi'i mdo",
"D317": "don rnam par nges pa zhes bya ba'i chos kyi rnam grangs",
"D318": "'phags pa don rgyas pa zhes bya ba'i chos kyi rnam grangs",
"D319": "'phags pa rmad du byung ba zhes bya ba chos kyi rnam grangs",
"D320": "'phags pa de bzhin gshegs pa'i gzugs brnyan bzhag pa'i phan yon yang dag par brjod pa zhes bya ba'i chos kyi rnam grangs",
"D321": "mchod rten bskor ba'i tshigs su bcad pa",
"D322": "gsal rgyal gyi tshigs su bcad pa",
"D323": "tshigs su bcad pa gcig pa",
"D324": "tshigs su bcad pa bzhi ba",
"D325": "klu'i rgyal po rnga sgra'i tshigs su bcad pa",
"D326": "ched du brjod pa'i tshoms",
"D327": "'phags pa skyes bu dam pa'i mdo",
"D328": "dga' bo rab tu byung ba'i mdo",
"D329": "lha'i mdo",
"D330": "lha'i mdo nyung ngu",
"D331": "zla ba'i mdo",
"D332": "khang bu brtsegs pa'i mdo",
"D333": "'phags pa gnas 'jog pa'i mdo zhes bya ba",
"D334": "'phags pa dga' ba can gyi mdo",
"D335": "'phags pa 'khar gsil gyi mdo",
"D336": "'khar gsil 'chang pa'i kun tu spyod pa'i cho ga",
"D337": "chos kyi 'khor lo'i mdo",
"D338": "las rnam par 'byed pa",
"D339": "las kyi rnam par 'gyur ba zhes bya ba'i chos kyi gzhung",
"D340": "las brgya tham pa",
"D341": "mdzangs blun zhes bya ba'i mdo",
"D342": "kun tu rgyu pa sen rings kyis zhus pa zhes bya ba'i mdo",
"D343": "gang po la sogs pa'i rtogs pa brjod pa brgya pa",
"D344": "'phags pa sangs rgyas kyi rtogs pa brjod pa shes ldan gyi mdo",
"D345": "'phag mo'i rtogs pa brjod pa zhes bya ba'i mdo",
"D346": "ma ga dha bzang mo'i rtogs pa brjod pa",
"D347": "bsod nams kyi stobs kyi rtogs pa brjod pa",
"D348": "zla 'od kyi rtogs pa brjod pa",
"D349": "dpal gyi sde'i rtogs pa brjod pa",
"D350": "gser mdog gi sngon gyi sbyor ba zhes bya ba",
"D351": "'phags pa rgyal bu don grub kyi mdo",
"D352": "tshangs pa'i dra ba'i mdo",
"D353": "thabs mkhas pa chen po sangs rgyas drin lan bsab pa'i mdo",
"D354": "'phags pa legs nyes kyi rgyu dang 'bras bu bstan pa zhes bya ba theg pa chen po'i mdo",
"D355": "dge ba dang mi dge ba'i las kyi rnam par smin pa bstan pa'i mdo",
"D356": "'phags pa zla ba'i snying pos zhus pa'i mdo las sangs rgyas kyi bstan pa gnas pa dang 'jig pa'i tshul lung bstan pa",
"D357": "'phags pa glang ru lung bstan pa zhes bya ba theg pa chen po'i mdo",
"D358": "stag rna'i rtogs pa brjod pa",
"D359": "mig bcu gnyis pa zhes bya ba'i mdo",
"D359a": "'phags pa dum bu zhe gnyis pa zhes bya ba'i mdo",
"D360": "'jam dpal ye shes sems dpa'i don dam pa'i mtshan yang dag par brjod pa",
"D361": "dbang mdor bstan pa",
"D362": "mchog gi dang po'i sangs rgyas las phyung ba rgyud kyi rgyal po dpal dus kyi 'khor lo zhes bya ba",
"D363": "dpal dus kyi 'khor lo'i rgyud phyi ma rgyud kyi snying po zhes bya ba",
"D364": "dpal dus kyi 'khor lo zhes bya ba'i rgyud kyi snying po",
"D365": "dbang gi rab tu byed pa",
"D366": "dpal sangs rgyas thams cad dang mnyam par sbyor ba mkha' 'gro ma sgyu ma bde ba'i mchog ces bya ba'i rgyud bla ma",
"D367": "rtog pa thams cad 'dus pa zhes bya ba sangs rgyas thams cad dang mnyam par sbyor ba mkha' 'gro sgyu ma bde ba'i mchog gi rgyud phyi ma'i phyi ma",
"D368": "rgyud kyi rgyal po dpal bde mchog nyung ngu zhes bya ba",
"D369": "mngon par brjod pa'i rgyud bla ma zhes bya ba",
"D370": "rgyud kyi rgyal po chen po dpal rdo rje mkha' 'gro zhes bya ba",
"D371": "rdo rje mkha' 'gro zhes bya ba'i rgyud phyi ma",
"D372": "dpal mkha' 'gro rgya mtsho chen po rnal 'byor ma'i rgyud kyi rgyal po zhes bya ba",
"D373": "dpal bde mchog 'byung ba zhes bya ba'i rgyud kyi rgyal po chen po",
"D374": "dpal khrag 'thung mngon par 'byung ba zhes bya ba",
"D375": "rnal 'byor ma'i kun tu spyod pa",
"D376": "rnal 'byor ma bzhi'i kha sbyor gyi rgyud ces bya ba",
"D377": "phag mo mngon par brjod pa bshad pa'i rgyud kyi phyi ma las phag mo mngon par byang chub pa zhes bya ba",
"D378": "mkha' 'gro ma thams cad kyi thugs gnyis su med pa bsam gyis mi khyab pa'i ye shes rdo rje phag mo mngon par 'byung ba'i rgyud kyi rgyal po zhes bya ba",
"D379": "mkha' 'gro ma thams cad kyi thugs gnyis su med pa bsam gyis mi khyab pa phag mo mngon par 'byung ba'i rgyud phyi m ardzogs rim bstan pa'i le'u",
"D380": "rig pa 'dzin ba rdo rje rnal 'byor ma'i sgrub thabs zhes bya ba",
"D381": "yang dag par sbyor ba zhes bya ba'i rgyud chen po",
"D382": "rgyud kyi rgyal po chen po dpal yang dag par sbyor ba'i thig le zhes bya ba",
"D383": "dpal gsang ba rdo rje rgyud kyi rgyal po",
"D384": "dpal gsang ba thams cad gcod pa'i rgyud kyi rgyal po",
"D385": "dpal 'khor lo sdom pa'i gsang ba bsam gyis mi khyab pa'i rgyud kyi rgyal po",
"D386": "dpal nam mkha' dang mnyam pa'i rgyud kyi rgyal po zhes bya ba",
"D387": "dpal nam mkha' chen po'i rgyud kyi rgyal po",
"D388": "dpal sku gsung thugs kyi rgyud kyi rgyal po",
"D389": "dpal rin chen phreng ba'i rgyud kyi rgyal po",
"D390": "dpal dam tshig chen po'i rgyud kyi rgyal po zhes bya ba",
"D391": "dpal stobs po che'i rgyud kyi rgyal po zhes bya ba",
"D392": "dpal ye shes gsang ba'i rgyud kyi rgyal po",
"D393": "dpal ye shes 'phreng ba rgyud kyi rgyal po",
"D394": "dpal ye shes 'bar ba'i rgyud kyi rgyal po",
"D395": "dpal zla ba'i phreng ba'i rgyud kyi rgyal po",
"D396": "dpal rin chen 'bar ba'i rgyud kyi rgyal po zhes bya ba",
"D397": "dpal nyi ma'i 'khor lo'i rgyud kyi rgyal po zhes bya ba",
"D398": "dpal ye shes rgyal po'i rgyud kyi rgyal po",
"D399": "dpal rdo rje mkha' 'gro gsang ba'i rgyud kyi rgyal po",
"D400": "dpal gsang ba me 'bar ba'i rgyud kyi rgyal po",
"D401": "dpal gsang ba bdud rtsi'i rgyud kyi rgyal po",
"D402": "dpal dur khrod rgyan pa'i rgyud kyi rgyal po",
"D403": "dpal rdo rje rgyal po chen po'i rgyud",
"D404": "dpal ye shes bsam pa'i rgyud kyi rgyal po",
"D405": "dpal chags pa'i rgyal po'i rgyud kyi rgyal po",
"D406": "dpal mkha' 'gro ma'i sdom pa'i rgyud kyi rgyal po zhes bya ba",
"D407": "dpal me'i phreng ba'i rgyud kyi rgyal po",
"D408": "dpal mkha' 'gro ma gsang ba 'bar ba'i rgyud kyi rgyal po",
"D409": "dpal rdo rje 'jigs byed rnam par 'joms pa'i rgyud kyi rgyal po",
"D410": "dpal stobs chen ye shes rgyal po'i rgyud kyi rgyal po",
"D411": "dpal rdo rje grub pa dra ba'i sdom pa'i rgyud kyi rgyal po",
"D412": "de bzhin gshegs pa thams cad kyi thugs kyi snying po don kyi rgyud",
"D413": "dpal 'khor lo sdom pa'i rgyud kyi rgyal po dur khrod kyi rgyan rmad du byung ba zhes bya ba",
"D414": "rgyud kyi rgyal po rnyog pa med pa zhes bya ba",
"D415": "dpal bde mchog nam mkha' dang mnyam pa'i rgyud kyi rgyal po zhes bya ba",
"D416": "dpal rdo rje nag po chen po khros pa'i mgon po gsang ba dngos grub 'byung ba zhes bya ba'i rgyud",
"D417": "kye'i rdo rje zhes bya ba rgyud kyi rgyal po",
"D418": "ki'i rdo rje mkha' 'gro ma dra ba'i sdom pa'i rgyud kyi rgyal po",
"D419": "'phags pa mkha' 'gro ma rdo rje gur zhes bya ba'i rgyud kyi rgyal po chen po'i brtag pa",
"D420": "dpal phyag rgya chen po'i thig le zhes bya ba rnal 'byor ma chen mo'i rgyud kyi rgyal po'i mnga' bdag",
"D421": "dpal ye shes snying po zhes bya ba rnal 'byor ma chen mo'i rgyud kyi rgyal po'i rgyal po",
"D422": "dpal ye shes thig le rnal 'byor ma'i rgyud kyi rgyal po chen po mchog tu rmad du byung ba zhes bya ba",
"D423": "dpal de kho na nyid kyi sgron ma zhes bya ba'i rnal 'byor chen mo'i rgyud kyi rgyal po",
"D424": "dpal sangs rgyas thod pa zhes bya ba rnal 'byor ma'i rgyud kyi rgyal po",
"D425": "dpal sgyu 'phrul chen po'i rgyud ces bya ba'i rgyud kyi rgyal po",
"D426": "rdo rje A ra li zhes bya ba'i rgyud kyi rgyal po chen po",
"D427": "ri gi A ra li'i rgyud kyi rgyal po zhes bya ba",
"D428": "rnal 'byor ma'i rgyud kyi rgyal po chen po dpal gdan bzhi pa zhes bya ba",
"D429": "dpal gdan bzhi pa'i bshad pa'i rgyud kyi rgyal po sngags kyi cha zhes bya ba",
"D430": "dpal gdan bzhi pa'i rnam par bshad pa'i rgyud kyi rgyal po zhes bya ba",
"D431": "dpal gtum po khro bo chen po'i rgyud kyi rgyal po dpa' bo gcig pa zhes bya ba",
"D432": "'phags pa mi g.yo ba'i rtog pa'i rgyud kyi rgyal po",
"D433": "khro bo'i rgyal po thams cad gsang sngags gsang ba'i rgyud ces bya ba",
"D434": "'phags pa mi g.yo ba'i gsang rgyud chen po",
"D435": "rdo rje bdud rtsi'i rgyud",
"D436": "rigs kyi 'jig rten mgon po lnga bcu pa zhes bya ba",
"D437": "'phags pa sgrol ma ku ru ku lle'i rtog pa",
"D438": "sgrol ma la phyag tshal nyi shu rtsa gcig gis bstod pa phan yon dang bcas pa",
"D439": "rdo rje phur pa rtsa ba'i rgyud kyi dum bu",
"D440": "nag po chen po zhes bya ba'i rgyud kyi rgyal po",
"D441": "ji bzhin brnyes pa nam mkha' dang mnyam pa zhes bya ba'i rgyud",
"D442": "de bzhin gshegs pa thams cad kyi sku gsung thugs kyi gsang chen gsang ba 'dus pa zhes bya ba brtag pa'i rgyal po chen po",
"D443": "rgyud phyi ma",
"D444": "dgongs pa lung bstan pa zhes bya ba'i rgyud",
"D445": "rnal 'byor chen po'i rgyud dpal rdo rje phreng ba mngon par brjod pa rgyud thams cad kyi snying po gsang ba rnam par phye ba zhes bya ba",
"D446": "lha mo bzhis yongs su zhus pa",
"D447": "ye shes rdo rje kun las btus pa zhes bya ba'i rgyud",
"D448": "phrin las thams cad 'byung ba'i sgro la 'dus pa don dam pa zhes bya ba rnal 'byor ma'i rgyud kyi rgyal po",
"D449": "phrin las thams cad 'bung ba 'dus pa don dam pa las phyi ma'i rgyud kyi rgyal po",
"D450": "dpal ye shes rdo rje kun las bsdus pa",
"D451": "dpal rdo rje snying po rgyan gyi rgyud ces bya ba",
"D452": "'phags pa gnyis su med pa mnyam pa nyid rnam par rgyal ba zhes bya ba'i rtog pa'i rgyal po chen po",
"D453": "dpal de bzhin gshegs pa thams cad kyi gsang ba rnal 'byor chen po rnam par rgyal ba zhes bya ba mnyam pa nyid gnyis su med pa'i rgyud kyi rgyal po rdo rje dpal mchog chen po brtag pa dang po",
"D454": "'phags pa lag na rdo rje gos sngon po can drag po gsum 'dul ba zhes bya ba'i rgyud",
"D455": "gsang ba'i rgyud rnams kyi rnam par 'byed pa drag po gsum 'dul zhes bya ba",
"D456": "lag na rdo rje gos sngon po can gyi cho ga rdo rje be con gyi rgyud",
"D457": "la na rdo rje gos sngon po can rdo rje gdengs pa'i rgyud khams gsum las rnam par rgyal ba zhes bya ba",
"D458": "dpal rdo rje gtum po thugs gsang ba'i rgyud",
"D459": "dpal rdo rje gtum po thugs gsang ba'i rgyud phyi ma",
"D460": "dpal rdo rje gtum po thugs gsang ba'i rgyud phyi ma'i phyi ma",
"D460a": "rmi lam mthong ba zhes bya ba'i gzungs",
"D461": "phyag na rdo rje gos sngon po can gnod sbyin drag po chen po rdo rje me lce'i rgyud ces bya ba",
"D462": "rdo rje snying po rdo rje lce 'bar ba zhes bya ba'i gzungs",
"D463": "dpal phyag na rdo rje gsang ba bstan pa'i rgyud",
"D464": "bcom ldan 'das phyag na rdo rje gsang ba mngon par bstan pa'i rgyud kyi rgyal po zhes bya ba",
"D465": "rdo rje bde khros rgyud kyi rgyal po",
"D466": "rgyud kyi rgyal po chen po sgyu 'phrul dra ba zhes bya ba",
"D467": "de bzhin gshegs pa thams cad kyi sku gsung thugs gshin rje gshed nag po zhes bya ba'i rgyud",
"D468": "dpal rdo rje 'jigs byed kyi chen po rgyud ces bya ba",
"D469": "dpal gshin rje'i gshed nag po'i rgyud kyi rgyal po rtog pa gsum pa zhes bya ba",
"D470": "dpal rdo rje 'jigs byed kyi rtog pa'i rgyud kyi rgyal po",
"D471": "gtam rgyud kyi rtog pa",
"D472": "te'u lo pa'i cho ga zhes bya ba",
"D473": "gshin rje gshed dgra nag po'i 'khor lo las thams cad grub par byed pa zhes bya ba'i rgyud kyi rgyal po",
"D474": "dpal gshin rje gshed dmar po zhes bya ba rgyud kyi rgyal po",
"D475": "dpal ldan gshin rje gshed dmar po'i rgyud kyi rgyal po zhes bya ba",
"D476": "dpal bcom ldan 'das ral pa gcig pa'i rgyud kyi rgyal po chen po zhes bya ba",
"D477": "dpal zla gsang thig le zhes bya ba rgyud kyi rgyal po chen po",
"D478": "dpal ldan gshin rje'i gshegs dmar po'i rgyud kyi rgyal po zhes bya ba",
"D479": "de bzhin gshegs pa thams cad kyi de kho na nyid bsdus pa zhes bya ba theg pa chen po'i mdo",
"D480": "gsang ba rnal 'byor chen po'i rgyud rdo rje rtse mo",
"D481": "thams cad gsang ba rgyud kyi rgyal po",
"D482": "'jig rten gsum las rnam par rgyal ba rtog pa'i rgyal po chen po",
"D483": "de bzhin gshegs pa dgra bcom pa yang dag par rdzogs pa'i sangs rgyas ngan song thams cad yongs su sbyong ba gzi brjid kyi rgyal po'i rtog pa zhes bya ba",
"D484": "mngon sbyod kyi las",
"D485": "de bzhin gshegs pa dgra bcom pa yang dag par rdzogs pa'i sangs rgyas ngan song thams cad yongs su sbyong ba gzi brjid kyi rgyal po'i brtag pa phyogs gcig pa zhes bya ba",
"D486": "rab tu gnas pa mdor bsdus pa'i rgyud",
"D487": "dpal mchog dang po zhes bya ba theg pa chen po'i rtog pa'i rgyal po",
"D488": "dpal mchog dang po'i sngags kyi rtog pa'i dum bu zhes bya ba",
"D489": "'phags pa shes rab kyi pha rol tu phyin pa'i tshul brgya lnga bcu pa rdzogs so",
"D490": "dpal rdo rje snying po rgyan ces bya ba'i rgyud kyi rgyal po chen po",
"D491": "'phags pa shes rab kyi pha rol tu phyin pa'i sgo nyi shu rtsa lnga pa zhes bya ba theg pa chen po'i mdo",
"D492": "de bzhin gshegs pa thams cad kyi sku dang gsung dang thugs kyi gsang ba rgyan gyi bkod pa zhes bya ba'i rgyud kyi rgyal po",
"D493": "'phags pa gsang ba nor bu thig le zhes bya ba'i mdo",
"D494": "rnam par snang mdzad chen po mngon par rdzogs par byang chub pa rnam par sprul ba byin gyis rlob pa shin tu rgyas pa mdo sde'i dbang po rgyal po zhes bya ba'i chos kyi rnam grangs",
"D495": "de bzhin gshegs pa thams cad kyi khro bo'i rgyal po 'phags pa mi g.yo ba de'i stobs dpag tu med pa brtul phod pa 'dul bar gsungs pa zhes bya ba'i rtog pa",
"D496": "'phags pa lag na rdo rje dbang bskur ba'i rgyud chen po",
"D497": "'phags pa lha mo brgyad kyi gzungs",
"D498": "bcom ldan 'das phyag na rdo rje gos sngon po can gyi rgyud ces bya ba",
"D499": "'phags pa lag na rdo rje gos sngon po can rdo rje sa 'og ces bya ba'i rgyud",
"D500": "rdo rje sa gsum du rgyu ba zhes bya ba'i rtog pa'i rgyal po",
"D501": "'phags pa lag na rdo rje gos sngon po can zhes bya ba 'jig rten gsum 'dul ba'i rgyud",
"D502": "dam tshig gsum bkod pa'i rgyal po zhes bya ba'i rgyud",
"D503": "'phags pa de bzhin gshegs pa bdun gyi sngon gyi smon lam gyi khyad par rgyas pa zhes bya ba theg pa chen po'i mdo",
"D504": "'phags pa bcom ldan 'das sman gyi bla baidurya'i 'do kyi sngon gyi smon lam gyi khyad par rgyas pa zhes bya ba theg pa chen po'i mdo",
"D505": "'phags pa de bzhin gshegs pa'i ting nge 'dzin gyi stobs bskyed pa baidurya'i 'od ces bya ba'i gzungs",
"D505a": "sman gtong ba'i tshe sman la sngags kyis gdab pa",
"D506": "'phags pa nor bu chen po rgyas pa'i gzhal med khang shin tu rab tu gnas pa gsang ba dam pa'i gsang ba'i cho ga zhib mo'i rgyal po zhes bya ba'i gzungs",
"D507": "'phags pa de bzhin gshegs pa thams cad kyi byin gyis rlabs kyi snying po gsang ba ring bsrel gyi za ma tog ces bya ba'i gzungs theg pa chen po'i mdo",
"D508": "byang chub snying po'i rgyan 'bum zhes bya ba'i gzungs",
"D509": "byang chub kyi snying po'i rgyan 'bum gyi gzungs",
"D510": "'phags pa 'od zer dri ma med pa rnam par dag pa'i 'od ces bya ba'i gzungs",
"D511": "'phags pa sangs rgyas bcu gnyis pa zhes bya ba theg pa chen po'i mdo",
"D512": "'phags pa sangs rgyas bdun pa zhes bya ba theg pa chen po'i mdo",
"D513": "'phags pa sangs rgyas thams cad kyi yan lag dang ldan pa zhes bya ba'i gzungs",
"D514": "'phags pa sangs rgyas kyi snying po zhes bya ba'i gzungs kyi chos kyi rnam grangs",
"D515": "'phags pa sangs rgyas kyi snying po zhes bya ba'i gzungs",
"D516": "'phags pa me tog brtsegs pa zhes bya ba'i gzungs",
"D517": "'phags pa dri ma med pa zhes bya ba'i gzungs",
"D518": "'phags pa tsan dan gyi yan lag ces bya ba'i gzungs",
"D519": "'phags pa rten cing 'brel bar 'byung ba'i snying po'i cho ga'i gzungs",
"D520": "'phags pa rten cing 'brel bar 'byung ba zhes bya ba theg pa chen po'i mdo",
"D521": "'phags pa rten cing 'brel bar 'byung ba'i snying po zhes bya ba",
"D522": "'phags pa ye shes ta la la zhes bya ba'i gzungs 'gro ba thams cad yongs su sbyong ba",
"D523": "'phags pa sa'i dbang po zhes bya ba'i gzungs",
"D524": "'phags pa gdon mi za ba zhes bya ba'i gzungs",
"D525": "'phags pa sgo mtha' yas pa sgrub pa zhes bya ba'i gzungs",
"D526": "'phags pa sgo drug pa zhes bya ba'i gzungs",
"D527": "'phags pa chos thams cad kyi yon tan bkod pa'i rgyal po zhes bya ba theg pa chen po'i mdo",
"D528": "'phags pa rig sngags kyi rgyal mo sgron ma mchog gi gzungs",
"D529": "'phags pa gzungs chen po",
"D530": "'phags pa shes rab kyi pha rol tu phyin pa yi ge nyung ngu zhes bya ba'i theg pa chen po'i mdo",
"D531": "bcom ldan 'das ma shes rab kyi pha rol tu phyin pa'i snying po",
"D532": "sangs rgyas bcom ldan 'das kyi mtshan brgya rtsa brgyad pa gzungs sngags dang bcas pa",
"D533": "'phags pa shakya thub pa'i snying po'i gzungs",
"D534": "'phags pa rnam par snang mdzad kyi snying po zhes bya ba'i gzungs",
"D535": "zla ba'i 'od kyi mtshan rjes su dran pa",
"D536": "de bzhin gshegs pa spyi'i snying po rjes su dran pa",
"D537": "sangs rgyas rin chen gtsug tor can gyi mtshan rjes su dran pa",
"D538": "mchod pa'i sprin zhes bya ba'i gzungs",
"D539": "'phags pa pad ma'i spyan zhes bya ba'i gzungs",
"D540": "su r'u pa zhes bya ba'i gzungs",
"D541": "'phags pa 'jig pa chen po brgyad las sgrol ba zhes bya ba'i gzungs",
"D542": "'phags pa khyad par can zhes bya ba'i gzungs",
"D543": "'phags pa 'jam dpal gyi rtsa ba'i rgyud",
"D544": "dpa' bo gcig bu grub pa zhes bya ba'i rgyud kyi rgyal po chen po",
"D545": "'phags pa 'jam dpal gyi zhal nas gsungs pa zhes bya ba'i gzungs",
"D546": "'phags pa 'jam dpal gyis dmod btsugs pa zhes bya ba'i gzungs",
"D547": "'jam dpal gyis dam bcas pa'i gzungs",
"D548": "'phags pa 'jam dpal gyi mtshan",
"D549": "rje btsun 'phags pa 'jam dpal gyis shes rab dang blo 'phel ba zhes bya ba'i gzungs",
"D550": "'phags pa 'jam dpal gyi sngags yi ge 'bru gcig pa'i cho ga",
"D551": "bcom ldan 'das kyis 'jam dpal rnon po la bstod pa",
"D552": "'jam dpal ngag gi dbang phyug la bu mo brgyad kyis bstod pa",
"D553": "'phags pa shes rab kyi pha rol tu phyin pa'i mtshan brgya rtsa brgyad pa zhes bya ba",
"D554": "'phags pa shes rab kyi pha rol tu phyin pa kau shi ka zhes bya'o",
"D555": "'phags pa gser 'od dam pa mchog tu rnam par rgyal ba'i mdo sde'i rgyal po theg pa chen po'i mdo",
"D556": "'phags pa gser 'od dam pa mdo sde'i dbang po'i rgyal po zhes bya ba theg pa chen po'i mdo",
"D557": "'phags pa gser 'od dam pa mdo sde'i dbang po'i rgyal po zhes bya ba theg pa chen po'i mdo",
"D558": "stong chen po rab tu 'joms pa zhes bya ba'i mdo",
"D559": "rig sngags kyi rgyal mo rma bya chen mo",
"D560": "'phags pa rig sngags kyi rgyal mo rma bya'i yang snying zhes bya ba",
"D561": "'phags pa rig sngags kyi rgyal mo so sor 'brang ba chen mo",
"D562": "bsil ba'i tshal chen po'i mdo",
"D563": "gsang sngags chen po rjes su 'dzin pa'i mdo",
"D564": "'phags ma 'od zer can zhes bya ba'i gzungs",
"D565": "sgyu ma'i 'od zer can 'byung ba'i rgyud las phyung ba'i rtog pa'i rgyal po zhes bya ba",
"D566": "'phags ma 'od zer can gyi dkyil 'khor gyi cho ga 'od zer can 'byung ba'i rgyud stong phrag bcu gnyis pa las phyung ba'i rtog pa'i snying po bdun brgya pa zhes bya ba",
"D567": "'phags pa rig sngags kyi rgyal mo chen mo rgyal ba can zhes bya ba",
"D568": "'phags pa rgyal ba can zhes bya ba'i gzungs",
"D569": "'phags pa dbang bskur ba zhes bya ba'i gzungs",
"D570": "'phags pa dbyig dang ldan pa zhes bya ba'i gzungs",
"D571": "'phags pa dug sel zhes bya ba'i rig sngags",
"D572": "klags pas grub pa bcom ldan 'das ma 'phags pa sor mo can zhes bya ba rig pa'i rgyal mo",
"D573": "'phags pa chos thams cad kyi yum zhes bya ba'i gzungs",
"D574": "'phags pa gtsug gi nor bu zhes bya ba'i gzungs",
"D575": "'phags pa yi ge drug pa'i rig sngags",
"D576": "'phags pa shes rab kyi pha rol tu phyin pa stong phrag brgya pa'i gzungs",
"D577": "'phags pa shes rab kyi pha rol tu phyin pa stong phrag nyi shu lnga pa'i gzungs",
"D578": "'phags pa shes rab kyi pha rol tu phyin pa brgyad stong pa'i gzungs",
"D579": "pha rol tu phyin pa drug gi snying po'i gzungs",
"D580": "pha rol tu phyin pa drug bzung bar 'gyur ba'i gzungs",
"D581": "pha rol tu phyin pa bcu thob par 'gyur ba'i gzungs",
"D582": "tshad med pa bzhi thob par 'gyur ba'i gzungs",
"D583": "shes rab kyi pha rol tu phyin pa stong phrag brgya ba bzung bar 'gyur ba'i gzungs",
"D584": "'phags pa phal po che bzung bar 'gyur ba'i gzungs",
"D585": "'phags pa sdong po bkod pa'i snying po",
"D586": "'phags pa ting nge 'dzin rgyal po'i mdo bzung bar 'gyur ba'i gzungs",
"D587": "'phags pa rma bya chen mo'i snying po",
"D588": "'phags pa so sor 'brang ma chen mo bzung bar 'gyur ba'i gzungs",
"D589": "'phags pa lang kar gshegs pa mdo thams cad klags par 'gyur ba'i gzungs",
"D590": "'phags pa de bzhin gshegs pa thams cad kyi gtsug tor nas byung ba gdugs dkar mo can zhes bya ba gzhan gyis mi thub ma phyir zlog pa'i rig sngags kyi rgyal mo chen mo",
"D591": "'phags pa de bzhin gshegs pa'i gtsug tor nas byung ba'i gdugs dkar mo can gzhan gyis mi thub ma phyir zlog pa chen mo mchog tu grub pa zhes bya ba'i gzungs",
"D592": "'phags pa de bzhin gshegs pa'i gtsug tor nas byung ba'i gdugs dkar mo can gzhan gyis mi thub ma zhes bya ba'i gzungs",
"D593": "'phags pa de bzhin gshegs pa'i gtsug tor nas byung ba'i gdugs dkar mo can gzhan gyis mi thub ma zhes bya ba'i gzungs",
"D594": "de bzhin gshegs pa thams cad kyi gtsug tor rnam par rgyal ba zhes bya ba'i gzungs rtog pa dang bcas pa",
"D595": "de bzhin gshegs pa thams cad kyi gtsug tor rnam par rgyal ba zhes bya ba'i gzungs rtog pa dang bcas pa",
"D596": "de bzhin gshegs pa thams cad kyi gtsug tor rnam par rgyal ba zhes bya ba'i gzungs rtog pa dang bcas pa",
"D597": "'phags pa ngan 'gro thams cad yongs su sbyong ba gtsug tor rnam par rgyal ba zhes bya ba'i gzungs",
"D598": "de bzhin gshegs pa thams cad kyi gtsug tor rnam par rgyal ma'i gzungs zhes bya ba'i rtog pa",
"D599": "kun nas sgor 'jug pa'i 'od zer gtsug tor dri ma med par snang ba de bzhin gshegs pa thams cad kyi snying po dang dam tshig la rnam par lta ba zhes bya ba'i gzungs",
"D600": "gtsug tor 'bar ba zhes bya ba'i gzungs",
"D601": "shes pas thams cad mthar phyin par grub pa'i mchod rten zhes bya ba'i gzungs",
"D602": "mchod rten gcig btab na bye ba btab par 'gyur ba'i gzungs",
"D603": "snying rje'i mchog ces bya ba'i gzungs",
"D604": "khro bo rnam par rgyal ba'i rtog pa gsang ba'i rgyud",
"D605": "'phags pa rdo rje 'jigs byed kyi gzungs zhes bya ba",
"D606": "'phags pa be con chen po zhes bya ba'i gzungs",
"D607": "'phags pa gzhan gyis mi thub pa rin po che phreng ba zhes bya ba",
"D608": "'phags pa bar du gcod pa thams cad rnam par sbyong ba zhes bya ba'i gzungs",
"D609": "'phags pa thams cad la mi 'jigs pa rab tu sbyin pa zhes bya ba'i gzungs",
"D610": "'phags pa 'gro lding ba'i rig sngags kyi rgyal po",
"D611": "tshigs su bcad pa gnyis pa'i gzungs",
"D612": "'phags pa rgyal mtshan gyi rtse mo'i dpung rgyan ces bya ba'i gzungs",
"D613": "'phags pa lha mo skul byed ma zhes bya ba'i gzungs",
"D614": "'phags pa sgo bzang po zhes bya ba'i gzungs",
"D615": "'phags pa bu mang po rton pa zhes bya ba'i gzungs",
"D616": "'phags pa ro langs bdun pa zhes bya ba'i gzungs",
"D617": "'phags pa mtshan mo bzang po zhes bya ba'i mdo",
"D618": "'phags pa mdangs phyir 'phrog pa zhes bya ba'i mdo",
"D619": "'phags pa mig rnam par sbyong ba zhes bya ba'i rig sngags",
"D620": "'phags pa mig nad rab tu zhi bar byed pa'i mdo",
"D621": "'phags pa gzhang 'brum rab tu zhi bar byed pa'i mdo",
"D622": "'phags pa nad thams cad rab tu zhi bar byed pa'i gzungs",
"D623": "'phags pa thams cad nad rab tu zhi bar byed pa'i gzungs",
"D624": "rims nad zhi ba'i gzungs",
"D625": "'phags pa rims nad rab tu zhi bar byed pa'i gzungs",
"D626": "'brum bu'i nad zhi bar byed pa'i gzungs",
"D627": "mdangs phyir mi 'phrog pa zhes bya ba",
"D628": "'phags pa yangs pa'i grong khyer du 'jug pa'i mdo chen po",
"D629": "'phags pa mi rgod rnam par 'joms pa zhes bya ba'i mdo",
"D630": "'phags pa bar du gcod pa thams cad sel ba'i gzungs sngags",
"D631": "'phags pa mi g.yo ba zhes bya ba'i gzungs",
"D632": "'phags pa rdo rje khro bo'i rgyal po'i rtog pa bsdus pa'i rgyud ces bya ba",
"D633": "'phags pa gser can zhes bya ba'i gzungs",
"D634": "'phags pa spyan ras gzigs dbang phyug gi mtshan brgya rtsa brgyad pa gzungs sngags dang bcas pa",
"D635": "'phags pa byams pa'i mtshan brgya rtsa brgyad pa gzungs sngags dang bcas pa",
"D636": "'phags pa nam mkha'i snying po'i mtshan brgya rtsa brgyad pa gzungs sngags dang bcas pa",
"D637": "'phags pa kun tu bzang po'i mtshan brgya rtsa brgyad pa gzungs sngags dang bcas pa",
"D638": "'phags pa lag na rdo rje'i mtshan brgya rtsa brgyad pa gzungs sngags dang bcas pa",
"D639": "'phags pa 'jam dpal gzhon nur gyur ba'i mtshan brgya rtsa brgyad pa gzungs sngags dang bcas pa",
"D640": "'phags pa sgrib pa thams cad rnam par sel ba'i mtshan brgya rtsa brgyad pa gzungs sngags dang bcas pa",
"D641": "'phags pa sa'i snying po'i mtshan brgya rtsa brgyad pa gzungs sngags dang bcas",
"D642": "'phags pa 'jam dpal gyi mtshan brgya rtsa brgyad pa zhes bya ba",
"D643": "'phags pa byams pas dam bcas pa zhes bya ba'i gzungs",
"D644": "'phags pa dkyil 'khor brgyad pa zhes bya ba'i theg pa chen po'i mdo",
"D645": "bdud rtsi 'byung ba zhes bya ba'i gzungs",
"D646": "yi dags kha nas me 'bar ba la skyabs mdzad pa zhes bya ba'i gzungs",
"D647": "yi dags mo kha 'bar ma dbugs dbyung ba'i gtor ma'i cho ga",
"D648": "'jur 'gegs zhes bya ba'i gzungs",
"D649": "ye shes skar mda'i snying po",
"D650": "shes rab bskyed pa zhes bya ba'i gzungs",
"D651": "thos pa 'dzin pa'i gzungs",
"D652": "'phags pa rgyal ba'i bla ma'i gzungs",
"D653": "mdo chen po 'dus pa chen po'i mdo zhes bya ba",
"D654": "'phags pa chos kyi rgya mtsho zhes bya ba'i gzungs",
"D655": "'phags pa bgegs sel ba'i gzungs",
"D656": "mdo chen po kun tu rgyu ba dang kun tu rgyu ba ma yin pa dang mthun pa'i mdo zhes bya ba",
"D657": "'phags pa sprin chen po",
"D658": "'phags pa sprin chen po rlung gi dkyil 'khor gyi le'u klu thams cad kyi snying po zhes bya ba theg pa chen po'i mdo",
"D659": "'phags pa klu'i rgyal po gzi can gyis zhus pa zhes bya ba'i gzungs",
"D660": "'phags ma gza' rnams kyi yum zhes bya ba'i gzungs",
"D661": "gza' rnams kyi yum zhes bya ba'i gzungs",
"D662": "'phags pa nor gyi rgyun ces bya ba'i gzungs",
"D663": "bcom ldan 'das ma nor rgyun ma'i rtog pa",
"D664": "bcom ldan 'das ma nor rgyun ma'i gzungs kyi rtog pa",
"D665": "'phags pa tshogs kyi bdag po'i snying po",
"D666": "tshogs kyi bdag po chen po'i rgyud ces bya ba",
"D667": "dpal nag po chen po'i rgyud",
"D668": "dpal mgon po nag po zhes bya ba'i gzungs",
"D669": "'phags pa nag po chen po'i gzungs rims nad thams cad las thar bar byed pa",
"D670": "lha mo nag mo chen mo'i gzungs",
"D671": "dpal lha mo nag mo'i bstod pa rgyal po'i rgyud",
"D672": "dpal lha mo nag mo'i mtshan brgya rtsa brgyad pa",
"D673": "lha'i dbang po brgya byin gyis bstod pa",
"D673a": "tshe dpag med kyi yang snying",
"D674": "'phags pa tshe dang ye shes dpag tu med pa zhes bya ba theg pa chen po'i mdo",
"D675": "'phags pa tshe dang ye shes dpag tu med pa zhes bya ba theg pa chen po'i mdo",
"D676": "'phags pa tshe dang ye shes dpag tu med pa'i snying po zhes bya ba'i gzungs",
"D677": "bcom ldan 'das snang ba mtha' yas kyi gzungs sngags",
"D678": "snang ba mtha' yas rjes su dran pa",
"D679": "'phags pa yon tan bsngags pa dpag tu med pa zhes bya ba'i gzungs",
"D680": "bde ldan gyi snying po",
"D681": "'phags pa spyan ras gzigs dbang phyug gi rtsa ba'i rgyud kyi rgyal po pad ma dra ba zhes bya ba",
"D682": "'phags pa don yod zhags pa'i snying po zhes bya ba theg pa chen po'i mdo",
"D683": "'phags pa don yod zhags pa'i snying po zhes bya ba'i gzungs",
"D684": "sred med kyis bus zhus pa 'phags pa sgyu ma chen mo rnam par rgyal ba thob par byed pa zhes bya ba'i gzungs",
"D685": "klus byin pa'i gzungs klu'i snying po zhes bya ba",
"D686": "'phags pa don yod pa'i zhags pa'i cho ga zhib mo'i rgyal po",
"D687": "'phags pa don yod zhags pa'i pha rol tu phyin pa drug yongs su rdzogs par byed pa zhes bya ba'i gzungs",
"D688": "sa bcu pa'i gzungs",
"D689": "'phags pa don yod zhags pa'i rtog pa'i rgyal po'i chog zhes bya ba",
"D690": "byang chub sems dpa' 'phags pa spyan ras gzigs dbang phyug lag pa stong dang mig stong dang ldan pa'i cho ga zhib mo",
"D691": "'phags pa byang chub sems dpa' spyan ras gzigs dbang phyug phyag stong spyan stong dang ldan pa thogs pa mi mnga' ba'i thugs rje chen po'i sems rgya cher yongs su rdzogs pa zhes bya ba'i gzungs",
"D692": "'phags pa spyan ras gzigs dbang phyug gi gsang ba'i mdzod thogs pa med pa'i yid bzhin gyi 'khor lo'i snying po zhes bya ba'i gzungs",
"D693": "'phags pa spyan ras gzigs dbang phyug zhal bcu gcig pa zhes ba'i gzungs",
"D694": "'phags pa zhal bcu gcig pa'i rig sngags kyi snying po zhes bya ba'i gzungs",
"D695": "'phags pa spyan ras gzigs kyi snying po",
"D696": "'phags pa spyan ras gzigs dbang phyug gi gzungs zhes bya ba",
"D697": "'phags pa ni la kang tha zhes bya ba'i gzungs",
"D698": "'phags pa snying rjes mi bshol ba zhes bya ba'i gzungs",
"D699": "'phags pa kun tu bzang po zhes bya ba'i gzungs",
"D700": "'jig rten dbang phyug gi rtog pa",
"D701": "padma cod pan zhes bya ba'i rgyud",
"D702": "seng ge sgra'i rgyud ces bya ba",
"D703": "'phags pa spyan ras gzigs dbang phyug seng ge sgra'i gzungs zhes bya ba",
"D704": "seng ge sgra'i gzungs",
"D705": "'phags pa spyan ras gzigs dbang phyug gi mtshan brgya rtsa rgyad pa",
"D706": "'phags pa spyan ras gzigs dbang phyug gi mtshan brgya rtsa brgyad pa zhes bya ba",
"D707": "'phags pa lus kyi dbyibs mdzes zhes bya ba'i gzungs",
"D708": "'phags pa gzhan gyis mi thub pa mi 'jigs pa sbyin pa zhes bya ba",
"D709": "gzhan gyis mi thub pa'i rig pa chen mo",
"D710": "stong 'gyur zhes bya ba'i gzungs",
"D711": "shu lo ka brgya lobs pa / [shlo ka brgya lobs pa]",
"D712": "shu lo ka brgya lobs pa / [shlo ka brgya lobs pa]",
"D713": "shu lo ka stong lobs pa'i gzungs",
"D714": "shu lo ka stong lobs pa'i gzungs",
"D715": "shu lo ka stong lobs pa'i gzungs",
"D716": "shu lo ka sum stong lobs pa'i gzungs",
"D717": "mi brjed pa'i gzungs",
"D718": "shes rab bskyed pa zhes bya ba'i gzungs",
"D719": "shes rab bskyed pa zhes bya ba'i gzungs",
"D720": "thos pa 'dzin pa'i gzungs",
"D721": "'phags pa de bzhin gshegs pa thams cad kyi byin gyi rlabs sems can la gzigs shing sangs rgyas kyi zhing gi bkod pa kun tu ston pa zhes bya ba theg pa chen po'i mdo",
"D722": "'phags pa spyan ras gzigs dbang phyug yid bzhin gyi nor bu'i rtog ba las smon lam 'byung ba",
"D723": "'phags pa spyan ras gzigs dbang phyug thugs rje chen po'i gzungs phan yon mdor bsdus pa zhes bya ba",
"D724": "ral pa gyen brdzes kyi rtog pa chen po byang chub sems dpa' chen po'i rnam par 'phrul pa le'u rab 'byams las bcom ldan 'das ma 'phags ma sgrol ma'i rtsa ba'i rtog pa zhes bya ba",
"D725": "'phags pa spyan ras gzigs dbang phyug gi yum zhes bya ba'i gzungs",
"D726": "de bzhin gshegs pa thams cad kyi yum sgrol ma las sna tshogs 'byung ba zhes bya ba'i rgyud",
"D727": "rje btsun ma 'phags ma sgrol ma'i mtshan brgya rtsa brgyad pa zhes bya ba",
"D728": "lha mo sgrol ma'i mtshan brgya rtsa brgyad pa zhes bya ba",
"D729": "'phags ma sgrol ma'i gzungs",
"D730": "'phags ma sgrol ma rang gis dam bcas pa zhes bya ba'i gzungs",
"D731": "'phags ma sgrol ma 'jig pa brgyad las skyob pa'i mdo",
"D732": "'phags pa grags ldan ma'i gzungs",
"D733": "'phags pa spyan ras gzigs dbang phyug ha ya gri ba'i gzungs",
"D734": "phyir zlog pa 'phags pa rnam par rgyal ba can zhes bya ba",
"D735": "'phags pa barna sha ba ri'i mdo",
"D736": "'phags pa ri khrod lo ma gyon pa zhes bya ba'i gzungs",
"D737": "'phags pa phyir zlog pa stobs can zhes bya ba",
"D738": "dpal lha mo sgra dbyangs la bstod pa",
"D739": "'phags ma lha mo chen mo dpal lung bstan pa",
"D740": "'phags pa dpal chen mo'i mdo",
"D741": "dpal gyi lha mo'i mtshan bcu gnyis pa",
"D742": "mchog thob pa'i rig sngags",
"D743": "'phags pa las kyi sgrib pa thams cad rnam par sbyong ba zhes bya ba'i gzungs",
"D744": "rdo rje sa 'og gi rgyud kyi rgyal po zhes bya ba",
"D745": "rje btsun ma 'phags ma sgrol ma'i mtshan brgya rtsa brgyad pa zhes bya ba",
"D746": "'phags pa rig pa mchog gi rgyud chen po",
"D747": "'byung po 'dul ba zhes bya ba'i rgyud kyi rgyal po chen po",
"D748": "'phags pa lag na rdo rje gos sngon po can gyi cho ga zhes bya ba'i gzungs",
"D749": "'phags pa lag na rdo rje'i mtshan brgyad pa gsang sngags dang bcas pa",
"D750": "rdo rje rnam par 'joms pa zhes bya ba'i gzungs",
"D751": "'phags pa rdo rje'i ri rab chen po'i rtse mo'i khang pa brtsegs pa'i gzungs",
"D752": "'phags pa rdo rje mi pham pa me ltar rab tu rmongs byed ces bya ba'i gzungs",
"D753": "rdo rje phra mo thogs pa med pa zhes bya ba'i gzungs",
"D754": "'phags pa lag na rdo rje bcu'i snying po",
"D755": "'phags pa bdud rtsi thabs sbyor gyi snying po bzhi pa zhes bya ba'i gzungs",
"D756": "khro bo'i rgyal po sme brtsegs la bstod pa'i sngags",
"D757": "'phags pa stobs po che zhes bya ba theg pa chen po'i mdo",
"D758": "'phags ma rdo rje lu gu rgyud ma'i rgyud kyi rtog pa",
"D759": "rdo rje mchu zhes bya ba klu'i dam tshig",
"D760": "rdo rje gnam lcags mchu zhes bya ba'i gzungs",
"D761": "'phags pa lcags mchu zhes bya ba'i gzungs",
"D762": "'phags pa lcags kyi mchu zhes bya ba'i gzungs",
"D763": "'phags pa lcags mchu nag po",
"D764": "'phags pa nor bu bzang po'i gzungs zhes bya ba",
"D765": "gnod sbyin nor bu bzang po'i rtog pa",
"D766": "gnod sbyin gyi sde dpon chen po gar mkhan mchog gi brtag pa",
"D767": "gnod sbyin gar mkhan mchog gi rgyud",
"D768": "'phags pa gnod 'dzin dpal zhes bya ba'i gzungs",
"D769": "'phags pa gnod 'dzin chu dbang snying rje can gyi gzungs bde byed ces bya ba",
"D770": "'phags pa gnod gnas dbang po ci ltar 'byung ba'i rtog pa zhes bya ba",
"D771": "'phags pa gnod 'dzin gyi mtshan brgya rtsa brgyad pa",
"D772": "'phags pa me kha la zhes bya ba'i gzungs",
"D773": "'phags pa rig sngags kyi rgyal po dbugs chen po zhes bya ba",
"D774": "rin po che brdar ba'i gzungs",
"D775": "bskor ba'i gzungs",
"D776": "'phags pa dkon mchog gi rten la bskor ba bya ba'i gzungs zhes bya ba",
"D777": "yon yongs su sbyong ba zhes bya ba / [yon tan yongs su sbyong ba zhes bya ba]",
"D778": "yon yongs su sbyong ba'i gzungs / [yon tan yongs su sbyong ba zhes bya ba'i gzungs]",
"D779": "phyag bya ba'i gzungs / [phyag byas pa'i gzungs]",
"D780": "gos brgya thob pa'i gzungs",
"D781": "mi dga' bar byed pa'i gzungs",
"D782": "ngan song thams cad yongs su sbyong ba zhes bya ba'i gzungs",
"D783": "skran zhi ba'i gzungs",
"D784": "ma zhu ba'i nad 'byang ba'i gzungs",
"D785": "'phags pa sdang ba thams cad rab tu zhi bar byed pa'i gzungs",
"D786": "sdig pa thams cad rab tu zhi bar byed pa zhes bya ba'i gzungs",
"D787": "khro ba zhi bar byed pa'i gzungs",
"D788": "'phags pa khros pa zhi bar byed pa'i gzungs",
"D789": "tshig btsan pa'i gzungs / [tshig brtson pa'i gzungs]",
"D790": "bdag bsrung ba'i gzungs",
"D791": "'phags pa yid du 'ong ba zhes bya ba",
"D792": "mgrin pa snyan pa'i gzungs",
"D793": "don thams cad grub pa'i gzungs",
"D794": "las grub pa'i gzungs",
"D795": "dug zhi bar byed pa zhes bya ba",
"D796": "bcings pa las grol ba'i gzungs",
"D797": "'phags pa bdud thams cad skrag par byed pa zhes bya ba",
"D798": "rma 'byor bar byed pa zhes bya ba'i gzungs sngags",
"D799": "me'i zug rngu rab tu zhi bar byed pa'i gzungs",
"D800": "mkhris pa'i nad sel ba'i sngags",
"D801": "bad kan gyi nad sel ba'i gzungs sngags",
"D802": "kshe ya'i nad sel ba'i sngags",
"D803": "'phags pa rims nad srog chags kyis mi tshugs pa zhes bya ba'i gzungs",
"D804": "lus kyi zag pa sbyin par btang ba'i gzungs",
"D805": "'phags pa dpung bzang gis zhus pa zhes bya ba'i rgyud",
"D806": "dkyil 'khor thams cad kyi spyi'i cho ga gsang ba'i rgyud",
"D807": "legs par grub par byed pa'i rgyud chen po las sgrub pa'i thabs rim par phye ba",
"D808": "bsam gtan gyi phyi ma rim par phye ba",
"D809": "'phags pa dgongs pa'i rgyud kyi phreng ba chen po byang chub sems dpa'i rnam par nges pa chen po bstan pa las nor bu chen po rin po che la mkhas pa bstan pa yongs su bsngo ba chen po'i rgyal po zhes bya ba",
"D810": "'phags pa yongs su bsngo ba'i rgyal po chen po sngags dang bcas pa",
"D811": "dpal legs par grub par byed pa yi rgyud chen po las 'byung ba'i smon lam",
"D812": "'phags pa spyan ras gzigs dbang phyug yid bzhin gyi nor bu'i rtog ba las smon lam 'byung ba",
"D813": "stong chen mo rab tu 'joms pa las gsungs pa'i smon lam",
"D814": "rig sngags kyi rgyal mo rma bya chen mo las gsungs pa'i smon lam dang bden tshig",
"D815": "sbyin pa'i rabs las 'byung ba'i smon lam",
"D816": "'phags pa yangs pa'i grong khyer du 'jug pa'i mdo las 'byung ba'i bde legs kyi tshigs su bcad pa",
"D817": "bde legs kyi tshigs su bcad pa",
"D818": "bde legs su 'gyur ba'i tshigs su bcad pa",
"D819": "lhas zhus pa'i bkra shis kyi tshigs su bcad pa",
"D820": "dpal rnal 'byor gyi rgyud kyi dkyil 'khor gyi lha de bzhin gshegs pa rigs lnga 'khor dang bcas pa lha sum bcu rtsa bdun gyi bkra shis kyi tshigs su bcad pa",
"D821": "sangs rgyas rabs bdun gyi bkra shis kyi tshigs su bcad pa / [sangs rgyas dpa' bo bdun gyi bkra shis]",
"D822": "de bzhin gshegs pa lnga'i bkra shis tshigs su bcad pa",
"D823": "rigs gsum gyi bkra shis",
"D824": "dkon mchog gsum gyi bkra shis kyi tshigs su bcad pa",
"D825": "rigs gsum gyi bkra shis",
"D826": "bkra shis kyi tshigs su bcad pa",
"D827": "dkon mchog gsum gyi bkra shis kyi tshigs su bcad pa",
"D828": "chos thams cad rdzogs pa chen po byang chub kyi sems kun byed rgyal po",
"D829": "de bzhin gshegs pa thams cad kyi thugs gsang ba'i ye shes don gyi snying po rdo rje bkod pa'i rgyud rnal 'byor grub pa'i lung kun 'dus rig pa'i mdo theg pa chen po mngon par rtogs pa chos kyi rnam grangs rnam par bkod pa zhes bya ba'i mdo",
"D830": "de bzhin gshegs pa thams cad kyi gsang ba gsang ba'i mdzod chen po mi zad pa gter gyi sgron ma brtul zhugs chen po bsgrub pa'i rgyud ye shes rngam pa glog gi 'khor lo zhes bya ba theg pa chen po'i mdo",
"D831": "de bzhin gshegs pa thams cad kyi thugs gsang ba'i ye shes don gyi snying po khro rdo rje'i rigs kun 'dus rig pa'i mdo rnal 'byor grub pa'i rgyud zhes bya ba theg pa chen po'i mdo",
"D832": "dpal gsang ba'i snying po de kho na nyid rnam par nges pa",
"D833": "rdo rje sems dpa'i sgyu 'phrul dra ba gsang ba thams cad kyi me long zhes bya ba'i rgyud",
"D834": "gsang ba'i snying po de kho na nyid nges pa",
"D835": "'phags pa thabs kyi zhags pa pad mo'i phreng zhes bya ba",
"D836": "lha mo sgyu 'phrul dra ba chen mo zhes bya ba'i rgyud",
"D837": "gsang ba'i snying po de kho na nyid nges pa'i bla ma chen po",
"D838": "'phags pa 'jam dpal las bzhi 'khor lo gsang ba'i rgyud",
"D839": "de bzhin gshegs pa thams cad kyi dgongs pa bla na med pa gsang ba rta mchog rol pa'i rgyud chen po zhes bya ba",
"D840": "dpal he ru ka snying rje rol pa'i rgyud gsang ba zab mo'i mchog ces bya ba",
"D841": "bdud rtsi chen po mchog gi lung",
"D841a": "rdo rje khros pa zhes sdang gcod pa",
"D842": "mkha' 'gro ma me lce 'bar ba'i rgyud",
"D842a": "mchod na rgyal ba rigs lnga rtag tu mchod",
"D843": "drag sngags 'dus pa rdo rje rtsa ba'i rgyud zhes bya ba",
"D844": "'jig rten mchod bstod sgrub pa rtsa ba'i rgyud zhes bya ba",
"D845": "bsdus pa'i rgyud kyi rgyal po dus kyi 'khor lo'i 'grel bshad / rtsa ba'i rgyud kyi rjes su 'jug pa stong phrag bcu gnyis pa dri ma med pa'i 'od ces bya ba",
"D846": "spyan 'dren rgyud gsum pa",
"D846a": "rgyud gsum pa",
"D847": "'phags pa dkon mchog ta la la'i gzungs zhes bya ba theg pa chen po'i mdo",
"D848": "'phags pa ye shes ta la la zhes bya ba'i gzungs 'gro ba thams cad yongs su sbyong ba",
"D849": "'phags pa tshe dang ye shes dpag tu med pa zhes bya ba theg pa chen po'i mdo",
"D850": "'phags pa tshe dang ye shes dpag tu med pa'i snying po zhes bya ba'i gzungs",
"D851": "'phags pa yon tan bsngags pa dpag tu med pa zhes bya ba'i gzungs",
"D852": "'phags pa sangs rgyas bdun pa zhes bya ba theg pa chen po'i mdo",
"D853": "'phags pa sangs rgyas bcu gnyis pa zhes bya ba theg pa chen po'i mdo",
"D854": "'phags pa sangs rgyas kyi snying po zhes bya ba'i gzungs kyi chos kyi rnam grangs",
"D855": "'phags pa sangs rgyas kyi snying po zhes bya ba'i gzungs",
"D856": "'phags pa sangs rgyas thams cad kyi yan lag dang ldan pa zhes bya ba'i gzungs",
"D857": "'phags pa tsan dan gyi yan lag ces bya ba'i gzungs",
"D858": "'phags pa rig sngags kyi rgyal mo sgron ma mchog gi gzungs",
"D859": "'phags pa dbang bskur ba zhes bya ba'i gzungs",
"D860": "'phags pa shakya thub pa'i snying po'i gzungs",
"D861": "'phags pa rnam par snang mdzad kyi snying po zhes bya ba'i gzungs",
"D862": "de bzhin gshegs pa sman gyi bla'i snying po'i gzungs",
"D863": "'phags pa rgyal ba'i bla ma'i gzungs",
"D864": "bcom ldan 'das snang ba mtha' yas kyi gzungs sngags",
"D865": "'phags pa 'od dpag med mthong ba'i gzungs",
"D866": "'phags pa pad ma'i spyan zhes bya ba'i gzungs",
"D867": "snang ba mtha' yas rjes su dran pa",
"D868": "zla ba'i 'od kyi mtshan rjes su dran pa",
"D869": "de bzhin gshegs pa spyi'i snying po rjes su dran pa",
"D870": "sangs rgyas rin chen gtsug tor can gyi mtshan rjes su dran pa",
"D871": "'phags pa dri ma med pa zhes bya ba'i gzungs",
"D872": "'phags pa khyad par can zhes bya ba'i gzungs",
"D873": "sangs rgyas bcom ldan 'das kyi mtshan brgya rtsa brgyad pa gzungs sngags dang bcas pa",
"D874": "'phags pa spyan ras gzigs dbang phyug gi mtshan brgya rtsa brgyad pa gzungs sngags dang bcas pa",
"D875": "'phags pa byams pa'i mtshan brgya rtsa brgyad pa gzungs sngags dang bcas pa",
"D876": "'phags pa nam mkha'i snying po'i mtshan brgya rtsa brgyad pa gzungs sngags dang bcas pa",
"D877": "'phags pa kun tu bzang po'i mtshan brgya rtsa brgyad pa gzungs sngags dang bcas pa",
"D878": "'phags pa lag na rdo rje'i mtshan brgya rtsa brgyad pa gzungs sngags dang bcas pa",
"D879": "'phags pa 'jam dpal gzhon nur gyur ba'i mtshan brgya rtsa brgyad pa gzungs sngags dang bcas pa",
"D880": "'phags pa sgrib pa thams cad rnam par sel ba'i mtshan brgya rtsa brgyad pa gzungs sngags dang bcas pa",
"D881": "'phags pa sa'i snying po'i mtshan brgya rtsa brgyad pa gzungs sngags dang bcas",
"D882": "'phags pa dkyil 'khor brgyad pa zhes bya ba'i theg pa chen po'i mdo",
"D883": "'phags pa de bzhin gshegs pa thams cad kyi byin gyis rlabs kyi snying po gsang ba ring bsrel gyi za ma tog ces bya ba'i gzungs theg pa chen po'i mdo",
"D884": "shes pas thams cad mthar phyin par grub pa'i mchod rten zhes bya ba'i gzungs",
"D885": "'phags pa nor bu chen po rgyas pa'i gzhal med khang shin tu rab tu gnas pa gsang ba dam pa'i gsang ba'i cho ga zhib mo'i rgyal po zhes bya ba'i gzungs",
"D886": "'phags pa me tog brtsegs pa zhes bya ba'i gzungs",
"D887": "'phags pa sa'i dbang po zhes bya ba'i gzungs",
"D888": "'phags pa gzungs chen po",
"D889": "bde ldan gyi snying po",
"D890": "'phags pa byams pas dam bcas pa zhes bya ba'i gzungs",
"D891": "'phags pa sgrib pa rnam par sel ba zhes bya ba'i gzungs",
"D892": "'phags pa 'jam dpal gyi zhal nas gsungs pa zhes bya ba'i gzungs",
"D893": "'phags pa 'jam dpal gyis dmod btsugs pa zhes bya ba'i gzungs",
"D894": "'phags pa 'jam dpal gyi mtshan",
"D895": "rje btsun 'phags pa 'jam dpal gyis shes rab dang blo 'phel ba zhes bya ba'i gzungs",
"D896": "'phags pa 'jam dpal gyi sngags yi ge 'bru gcig pa'i cho ga",
"D897": "'phags pa byang chub sems dpa' spyan ras gzigs dbang phyug phyag stong spyan stong dang ldan pa thogs pa mi mnga' ba'i thugs rje chen po'i sems rgya cher yongs su rdzogs pa zhes bya ba'i gzungs",
"D898": "'phags pa spyan ras gzigs dbang phyug gi gsang ba'i mdzod thogs pa med pa'i yid bzhin gyi 'khor lo'i snying po zhes bya ba'i gzungs",
"D899": "'phags pa spyan ras gzigs dbang phyug zhal bcu gcig pa zhes ba'i gzungs",
"D900": "'phags pa spyan ras gzigs dbang phyug gi mtshan brgya rtsa rgyad pa",
"D901": "'phags pa don yod zhags pa'i snying po zhes bya ba theg pa chen po'i mdo",
"D902": "sa bcu pa'i gzungs",
"D903": "'phags pa don yod zhags pa'i pha rol tu phyin pa drug yongs su rdzogs par byed pa zhes bya ba'i gzungs",
"D904": "'phags pa kun tu bzang po zhes bya ba'i gzungs",
"D905": "'phags pa ni la kang tha zhes bya ba'i gzungs",
"D906": "'phags pa spyan ras gzigs dbang phyug ha ya gri ba'i gzungs",
"D907": "'phags pa me kha la zhes bya ba'i gzungs",
"D908": "'phags pa snying rjes mi bshol ba zhes bya ba'i gzungs",
"D909": "'phags pa spyan ras gzigs dbang phyug gi yum zhes bya ba'i gzungs",
"D910": "'phags pa spyan ras gzigs dbang phyug gi gzungs zhes bya ba",
"D911": "'phags pa spyan ras gzigs kyi snying po",
"D912": "seng ge sgras dam bcas pa'i gzungs",
"D913": "snying rje'i mchog ces bya ba'i gzungs",
"D914": "'phags pa sgo mtha' yas pa sgrub pa zhes bya ba'i gzungs",
"D915": "'phags pa sgo bzang po zhes bya ba'i gzungs",
"D916": "'phags pa sgo drug pa zhes bya ba'i gzungs",
"D917": "'phags pa yi ge drug pa'i rig sngags",
"D918": "tshigs su bcad pa gnyis pa'i gzungs",
"D919": "'phags pa lus kyi dbyibs mdzes zhes bya ba'i gzungs",
"D920": "byang chub kyi snying po'i rgyan 'bum gyi gzungs",
"D921": "mchod rten gcig btab na bye ba btab par 'gyur ba'i gzungs",
"D922": "'phags pa gtsug gi nor bu zhes bya ba'i gzungs",
"D923": "'phags pa rgyal mtshan gyi rtse mo'i dpung rgyan ces bya ba'i gzungs",
"D924": "'phags pa gser can zhes bya ba'i gzungs",
"D925": "'phags pa thams cad la mi 'jigs pa rab tu sbyin pa zhes bya ba'i gzungs",
"D926": "'phags pa bar du gcod pa thams cad rnam par sbyong ba zhes bya ba'i gzungs",
"D927": "'phags pa 'gro lding ba'i rig sngags kyi rgyal po",
"D928": "'phags pa gzhan gyis mi thub pa mi 'jigs pa sbyin pa zhes bya ba",
"D929": "'phags pa gzhan gyis mi thub pa rin po che phreng ba zhes bya ba",
"D930": "stong 'gyur zhes bya ba'i gzungs",
"D931": "'phags pa 'jig pa chen po brgyad las sgrol ba zhes bya ba'i gzungs",
"D932": "'phags pa shes rab kyi pha rol tu phyin pa stong phrag brgya pa'i gzungs",
"D933": "'phags pa shes rab kyi pha rol tu phyin pa stong phrag nyi shu lnga pa'i gzungs",
"D934": "'phags pa shes rab kyi pha rol tu phyin pa brgyad stong pa'i gzungs",
"D935": "pha rol tu phyin pa drug gi snying po'i gzungs",
"D936": "pha rol tu phyin pa drug bzung bar 'gyur ba'i gzungs",
"D937": "pha rol tu phyin pa bcu thob par 'gyur ba'i gzungs",
"D938": "tshad med pa bzhi thob par 'gyur ba'i gzungs",
"D939": "shes rab kyi pha rol tu phyin pa stong phrag brgya ba bzung bar 'gyur ba'i gzungs",
"D940": "'phags pa phal po che bzung bar 'gyur ba'i gzungs",
"D941": "'phags pa sdong po bkod pa'i snying po",
"D942": "'phags pa ting nge 'dzin rgyal po'i mdo bzung bar 'gyur ba'i gzungs",
"D943": "'phags pa rma bya chen mo'i snying po",
"D944": "'phags pa so sor 'brang ma chen mo bzung bar 'gyur ba'i gzungs",
"D945": "'phags pa lang kar gshegs pa mdo thams cad klags par 'gyur ba'i gzungs",
"D946": "'phags pa rdo rje'i ri rab chen po'i rtse mo'i khang pa brtsegs pa'i gzungs",
"D947": "'phags pa stobs po che zhes bya ba theg pa chen po'i mdo",
"D948": "'phags pa lag na rdo rje gos sngon po can gyi cho ga zhes bya ba'i gzungs",
"D949": "rdo rje rnam par 'joms pa zhes bya ba'i gzungs",
"D950": "'phags pa lag na rdo rje'i mtshan brgyad pa gsang sngags dang bcas pa",
"D951": "'phags pa lag na rdo rje bcu'i snying po",
"D952": "rmi lam mthong ba zhes bya ba'i gzungs",
"D953": "phyag na rdo rje gnod sbyin gyi bdag po'i gzungs",
"D954": "'phags pa rdo rje mi pham pa me ltar rab tu rmongs byed ces bya ba'i gzungs",
"D955": "rdo rje phra mo thogs pa med pa zhes bya ba'i gzungs",
"D956": "'phags pa rdo rje 'jigs byed kyi gzungs zhes bya ba",
"D957": "'phags pa bdud rtsi thabs sbyor gyi snying po bzhi pa zhes bya ba'i gzungs",
"D958": "'phags pa be con chen po zhes bya ba'i gzungs",
"D959": "'phags pa bgegs sel ba'i gzungs",
"D960": "'phags pa phyir zlog pa stobs can zhes bya ba",
"D961": "'phags pa mi rgod rnam par 'joms pa zhes bya ba'i mdo",
"D962": "gtsug tor 'bar ba zhes bya ba'i gzungs",
"D963": "'phags pa mi g.yo ba zhes bya ba'i gzungs",
"D964": "rdo rje mchu zhes bya ba klu'i dam tshig",
"D965": "rdo rje gnam lcags mchu zhes bya ba'i gzungs",
"D966": "'phags pa lcags mchu nag po",
"D967": "'phags pa mdangs phyir 'phrog pa zhes bya ba'i mdo",
"D968": "phyir zlog pa 'phags pa rnam par rgyal ba can zhes bya ba",
"D969": "'phags pa rig sngags kyi rgyal po dbugs chen po zhes bya ba",
"D970": "'phags pa nor bu bzang po'i gzungs zhes bya ba",
"D971": "'phags pa gnod 'dzin chu dbang snying rje can gyi gzungs bde byed ces bya ba",
"D972": "'phags pa gnod 'dzin gyi mtshan brgya rtsa brgyad pa",
"D973": "'phags pa gnod 'dzin dpal zhes bya ba'i gzungs",
"D974": "'phags pa mtshan mo bzang po zhes bya ba'i mdo",
"D975": "'phags pa chos kyi rgya mtsho zhes bya ba'i gzungs",
"D976": "'phags pa bu mang po rton pa zhes bya ba'i gzungs",
"D977": "'phags pa gdon mi za ba zhes bya ba'i gzungs",
"D978": "gzhan gyis mi thub pa'i rig pa chen mo",
"D979": "'phags pa rten cing 'brel bar 'byung ba'i snying po'i cho ga'i gzungs",
"D980": "'phags pa rten cing 'brel bar 'byung ba zhes bya ba theg pa chen po'i mdo",
"D981": "'phags pa rten cing 'brel bar 'byung ba'i snying po zhes bya ba",
"D982": "'phags pa 'od zer dri ma med pa rnam par dag pa'i 'od ces bya ba'i gzungs",
"D983": "kun nas sgor 'jug pa'i 'od zer gtsug tor dri ma med par snang ba de bzhin gshegs pa thams cad kyi snying po dang dam tshig la rnam par lta ba zhes bya ba'i gzungs",
"D984": "'phags pa ngan 'gro thams cad yongs su sbyong ba gtsug tor rnam par rgyal ba zhes bya ba'i gzungs",
"D985": "'phags pa de bzhin gshegs pa thams cad kyi gtsug tor nas byung ba gdugs dkar mo can zhes bya ba gzhan gyis mi thub ma phyir zlog pa'i rig sngags kyi rgyal mo chen mo",
"D986": "'phags pa de bzhin gshegs pa'i gtsug tor nas byung ba'i gdugs dkar mo can gzhan gyis mi thub ma zhes bya ba'i gzungs",
"D987": "dpal lha mo gtsug tor rol pa'i tan tra",
"D988": "'phags ma 'od zer can zhes bya ba'i gzungs",
"D989": "'phags pa lha mo skul byed ma zhes bya ba'i gzungs",
"D990": "'phags pa dug sel zhes bya ba'i rig sngags",
"D991": "'phags pa dbyig dang ldan pa zhes bya ba'i gzungs",
"D992": "'phags pa grags ldan ma'i gzungs",
"D993": "klags pas grub pa bcom ldan 'das ma 'phags pa sor mo can zhes bya ba rig pa'i rgyal mo",
"D994": "'phags pa barna sha ba ri'i mdo",
"D995": "'phags pa ri khrod lo ma gyon pa zhes bya ba'i gzungs",
"D996": "'phags pa chos thams cad kyi yum zhes bya ba'i gzungs",
"D997": "'phags ma gza' rnams kyi yum zhes bya ba'i gzungs",
"D998": "gza' rnams kyi yum zhes bya ba'i gzungs",
"D999": "'phags pa lha mo brgyad kyi gzungs",
"D1000": "rje btsun ma 'phags ma sgrol ma'i mtshan brgya rtsa brgyad pa zhes bya ba",
"D1001": "'phags ma sgrol ma'i gzungs",
"D1002": "'phags ma sgrol ma rang gis dam bcas pa zhes bya ba'i gzungs",
"D1003": "'phags pa rig sngags kyi rgyal mo chen mo rgyal ba can zhes bya ba",
"D1004": "'phags pa rgyal ba can zhes bya ba'i gzungs",
"D1005": "'phags pa dpal chen mo'i mdo",
"D1006": "dpal gyi lha mo'i mtshan bcu gnyis pa",
"D1007": "'phags pa nor gyi rgyun ces bya ba'i gzungs",
"D1008": "'phags pa mig rnam par sbyong ba zhes bya ba'i rig sngags",
"D1009": "'phags pa las kyi sgrib pa thams cad rnam par sbyong ba zhes bya ba'i gzungs",
"D1010": "'phags pa bar du gcod pa thams cad sel ba'i gzungs sngags",
"D1011": "yon yongs su sbyong ba zhes bya ba / [yon tan yongs su sbyong ba zhes bya ba]",
"D1012": "yon yongs su sbyong ba'i gzungs / [yon tan yongs su sbyong ba zhes bya ba'i gzungs]",
"D1013": "ngan song thams cad yongs su sbyong ba zhes bya ba'i gzungs",
"D1014": "'phags pa nad thams cad rab tu zhi bar byed pa'i gzungs",
"D1015": "'phags pa thams cad nad rab tu zhi bar byed pa'i gzungs",
"D1016": "'phags pa rims nad rab tu zhi bar byed pa'i gzungs",
"D1017": "rims nad zhi ba'i gzungs",
"D1018": "'phags pa mig nad rab tu zhi bar byed pa'i mdo",
"D1019": "'brum bu'i nad zhi bar byed pa'i gzungs",
"D1020": "'phags pa gzhang 'brum rab tu zhi bar byed pa'i mdo",
"D1021": "ma zhu ba'i nad 'byang ba'i gzungs",
"D1022": "'phags pa sdang ba thams cad rab tu zhi bar byed pa'i gzungs",
"D1023": "sdig pa thams cad rab tu zhi bar byed pa zhes bya ba'i gzungs",
"D1024": "sdug bsngal thams cad rab tu zhi bar byed pa zhes bya ba'i gzungs",
"D1025": "khro ba zhi bar byed pa'i gzungs",
"D1026": "'phags pa khros pa zhi bar byed pa'i gzungs",
"D1027": "tshig btsan pa'i gzungs / [tshig brtson pa'i gzungs]",
"D1028": "bdag bsrung ba'i gzungs",
"D1029": "don thams cad grub pa'i gzungs",
"D1030": "las grub pa'i gzungs",
"D1031": "gos brgya thob pa'i gzungs",
"D1032": "mi dga' bar byed pa'i gzungs",
"D1033": "'phags pa yid du 'ong ba zhes bya ba",
"D1034": "mgrin pa snyan pa'i gzungs",
"D1035": "bcings pa las grol ba'i gzungs",
"D1036": "mchog thob pa'i rig sngags",
"D1037": "shes rab bskyed pa zhes bya ba'i gzungs",
"D1038": "shes rab bskyed pa zhes bya ba'i gzungs",
"D1039": "shes rab bskyed pa zhes bya ba'i gzungs",
"D1040": "thos pa 'dzin pa'i gzungs",
"D1041": "thos pa 'dzin pa'i gzungs",
"D1042": "shu lo ka brgya lobs pa / [shlo ka brgya lobs pa]",
"D1043": "shu lo ka brgya lobs pa / [shlo ka brgya lobs pa]",
"D1044": "shu lo ka stong lobs pa'i gzungs",
"D1045": "shu lo ka stong lobs pa'i gzungs",
"D1046": "shu lo ka stong lobs pa'i gzungs",
"D1047": "shu lo ka sum stong lobs pa'i gzungs",
"D1048": "mi brjed pa'i gzungs",
"D1049": "phyag bya ba'i gzungs / [phyag byas pa'i gzungs]",
"D1050": "'phags pa rims nad srog chags kyis mi tshugs pa zhes bya ba'i gzungs",
"D1051": "dug zhi bar byed pa zhes bya ba",
"D1052": "mdangs phyir mi 'phrog pa zhes bya ba",
"D1053": "'phags pa bdud thams cad skrag par byed pa zhes bya ba",
"D1054": "rma 'byor bar byed pa zhes bya ba'i gzungs sngags",
"D1055": "me'i zug rngu rab tu zhi bar byed pa'i gzungs",
"D1056": "mkhris pa'i nad sel ba'i sngags",
"D1057": "bad kan gyi nad sel ba'i gzungs sngags",
"D1058": "kshe ya'i nad sel ba'i sngags",
"D1058a": "stong chen mo nas phyung ba'i sman la sngags btab pa",
"D1059": "stong chen po rab tu 'joms pa zhes bya ba'i mdo",
"D1059a": "sman la sngags kyis gdab pa",
"D1060": "skran zhi ba'i gzungs",
"D1061": "mdo chen po kun tu rgyu ba dang kun tu rgyu ba ma yin pa dang mthun pa'i mdo zhes bya ba",
"D1062": "mdo chen po 'dus pa chen po'i mdo zhes bya ba",
"D1063": "'phags pa sprin chen po",
"D1064": "'phags pa sprin chen po rlung gi dkyil 'khor gyi le'u klu thams cad kyi snying po zhes bya ba theg pa chen po'i mdo",
"D1065": "'phags pa klu'i rgyal po gzi can gyis zhus pa zhes bya ba'i gzungs",
"D1066": "'phags pa sdong po rgyan gyi mchog ces bya ba'i gzungs",
"D1067": "sangs rgyas kyi chos gsal zhing yangs pa snang brgyad ces bya ba'i mdo",
"D1068": "mchod pa'i sprin zhes bya ba'i gzungs",
"D1069": "phyag bya ba'i gzungs",
"D1070": "bstod pa'i gzungs",
"D1071": "mchod pa byin gyis brlab pa'i gzungs",
"D1072": "mchod pa'i sprin zhes bya ba'i gzungs",
"D1073": "phyags bya ba'i gzungs",
"D1074": "rin po che brdar ba'i gzungs",
"D1075": "bskor ba'i gzungs",
"D1076": "'phags pa dkon mchog gi rten la bskor ba bya ba'i gzungs zhes bya ba",
"D1077": "ye shes skar mda'i snying po",
"D1078": "su r'u pa zhes bya ba'i gzungs",
"D1079": "yi dags mo kha 'bar ma dbugs dbyung ba'i gtor ma'i cho ga",
"D1080": "yi dags kha nas me 'bar ba la skyabs mdzad pa zhes bya ba'i gzungs",
"D1081": "'jur 'gegs zhes bya ba'i gzungs",
"D1082": "lus kyi zag pa sbyin par btang ba'i gzungs",
"D1083": "'phags pa ro langs bdun pa zhes bya ba'i gzungs",
"D1084": "'phags pa tshogs kyi bdag po'i snying po",
"D1085": "dpal mgon po nag po zhes bya ba'i gzungs",
"D1086": "'phags pa nag po chen po'i gzungs rims nad thams cad las thar bar byed pa",
"D1087": "lha mo nag mo chen mo'i gzungs",
"D1088": "dpal lha mo nag mo'i mtshan brgya rtsa brgyad pa",
"D1089": "lha'i dbang po brgya byin gyis bstod pa",
"D1090": "nad kyi bdag mo la bstod pa",
"D1091": "lha mo nam gru la bstod pa",
"D1092": "dpal lha mo sgra dbyangs la bstod pa",
"D1093": "'phags pa yangs pa'i grong khyer du 'jug pa'i mdo chen po",
"D1094": "'phags pa spyan ras gzigs dbang phyug yid bzhin gyi nor bu'i rtog ba las smon lam 'byung ba",
"D1095": "'phags pa bzang po spyod pa'i smon lam gyi rgyal po",
"D1096": "'phags pa byams pa'i smon lam / ['phags pa byams pa'i smon lam gyi rgyal po]",
"D1097": "mchog gi spyod pa'i smon lam",
"D1098": "stong chen mo rab tu 'joms pa las gsungs pa'i smon lam",
"D1099": "rig sngags kyi rgyal mo rma bya chen mo las gsungs pa'i smon lam dang bden tshig",
"D1100": "lhas zhus pa'i bkra shis kyi tshigs su bcad pa",
"D1101": "bde legs kyi tshigs su bcad pa",
"D1102": "bde legs su 'gyur ba'i tshigs su bcad pa",
"D1103": "bkra shis kyi tshigs su bcad pa",
"D1104": "sangs rgyas rabs bdun gyi bkra shis kyi tshigs su bcad pa / [sangs rgyas dpa' bo bdun gyi bkra shis]",
"D1105": "de bzhin gshegs pa lnga'i bkra shis tshigs su bcad pa",
"D1106": "rigs gsum gyi bkra shis",
"D1107": "shis par brjod pa'i tshigs su bcad pa",
"D1108": "dkon mchog gsum gyi bkra shis kyi tshigs su bcad pa",
}
